// This file is generated by scripts/openapi-query-options.mjs.
// Source: src/openapi/openapi.yaml (repository root)
// OpenAPI: forklift API 0.1.0

import { queryOptions } from "@tanstack/react-query";

import { type HttpClient } from "@/lib/http/client/http-client";
import { openApiQueryKeys } from "@/query/v1/openapi-query-keys";
import {
  listRoles,
} from "@/services/v1/roles/api";

export function createRolesOpenApiQueryOptions(client: HttpClient) {
  return {
    listRoles: () =>
      queryOptions({
        queryKey: openApiQueryKeys.listRoles(),
        queryFn: ({ signal }) =>
          listRoles({ signal, client }),
      }),
  } as const;
}
