// This file is generated by scripts/openapi-query-options.mjs.
// Source: src/openapi/openapi.yaml (repository root)
// OpenAPI: forklift API 0.1.0

import { queryOptions } from "@tanstack/react-query";

import { type HttpClient } from "@/lib/http/client/http-client";
import { openApiQueryKeys } from "@/query/v1/openapi-query-keys";
import {
  getRepository,
  getRepositoryDangling,
  getRepositoryOciDetail,
  getRepositoryUploads,
  getRepositoryUpstreamHealth,
  listRepositories,
  listRepositoryArtifacts,
  listRepositoryArtifactsLabels,
  listRepositoryAuditLogs,
  listRepositoryNames,
  listRepositoryOciTags,
  listRepositoryPermissions,
  listRepositoryTokens,
} from "@/services/v1/repositories/api";
import type {
  GetRepositoryDanglingRequest,
  GetRepositoryOciDetailRequest,
  GetRepositoryRequest,
  GetRepositoryUploadsRequest,
  GetRepositoryUpstreamHealthRequest,
  ListRepositoryArtifactsLabelsRequest,
  ListRepositoryArtifactsRequest,
  ListRepositoryAuditLogsRequest,
  ListRepositoryOciTagsRequest,
  ListRepositoryPermissionsRequest,
  ListRepositoryTokensRequest,
} from "@/services/v1/repositories/types";
export function createRepositoriesOpenApiQueryOptions(client: HttpClient) {
  return {
    listRepositories: () =>
      queryOptions({
        queryKey: openApiQueryKeys.listRepositories(),
        queryFn: ({ signal }) =>
          listRepositories({ signal, client }),
      }),
    getRepository: (params: GetRepositoryRequest) =>
      queryOptions({
        queryKey: openApiQueryKeys.getRepository(params),
        queryFn: ({ signal }) =>
          getRepository(params, { signal, client }),
      }),
    listRepositoryAuditLogs: (params: ListRepositoryAuditLogsRequest) =>
      queryOptions({
        queryKey: openApiQueryKeys.listRepositoryAuditLogs(params),
        queryFn: ({ signal }) =>
          listRepositoryAuditLogs(params, { signal, client }),
      }),
    listRepositoryNames: () =>
      queryOptions({
        queryKey: openApiQueryKeys.listRepositoryNames(),
        queryFn: ({ signal }) =>
          listRepositoryNames({ signal, client }),
      }),
    listRepositoryOciTags: (params: ListRepositoryOciTagsRequest) =>
      queryOptions({
        queryKey: openApiQueryKeys.listRepositoryOciTags(params),
        queryFn: ({ signal }) =>
          listRepositoryOciTags(params, { signal, client }),
      }),
    getRepositoryOciDetail: (params: GetRepositoryOciDetailRequest) =>
      queryOptions({
        queryKey: openApiQueryKeys.getRepositoryOciDetail(params),
        queryFn: ({ signal }) =>
          getRepositoryOciDetail(params, { signal, client }),
      }),
    listRepositoryArtifacts: (params: ListRepositoryArtifactsRequest) =>
      queryOptions({
        queryKey: openApiQueryKeys.listRepositoryArtifacts(params),
        queryFn: ({ signal }) =>
          listRepositoryArtifacts(params, { signal, client }),
      }),
    getRepositoryUploads: (params: GetRepositoryUploadsRequest) =>
      queryOptions({
        queryKey: openApiQueryKeys.getRepositoryUploads(params),
        queryFn: ({ signal }) =>
          getRepositoryUploads(params, { signal, client }),
      }),
    getRepositoryDangling: (params: GetRepositoryDanglingRequest) =>
      queryOptions({
        queryKey: openApiQueryKeys.getRepositoryDangling(params),
        queryFn: ({ signal }) =>
          getRepositoryDangling(params, { signal, client }),
      }),
    listRepositoryArtifactsLabels: (params: ListRepositoryArtifactsLabelsRequest) =>
      queryOptions({
        queryKey: openApiQueryKeys.listRepositoryArtifactsLabels(params),
        queryFn: ({ signal }) =>
          listRepositoryArtifactsLabels(params, { signal, client }),
      }),
    getRepositoryUpstreamHealth: (params: GetRepositoryUpstreamHealthRequest) =>
      queryOptions({
        queryKey: openApiQueryKeys.getRepositoryUpstreamHealth(params),
        queryFn: ({ signal }) =>
          getRepositoryUpstreamHealth(params, { signal, client }),
      }),
    listRepositoryPermissions: (params: ListRepositoryPermissionsRequest) =>
      queryOptions({
        queryKey: openApiQueryKeys.listRepositoryPermissions(params),
        queryFn: ({ signal }) =>
          listRepositoryPermissions(params, { signal, client }),
      }),
    listRepositoryTokens: (params: ListRepositoryTokensRequest) =>
      queryOptions({
        queryKey: openApiQueryKeys.listRepositoryTokens(params),
        queryFn: ({ signal }) =>
          listRepositoryTokens(params, { signal, client }),
      }),
  } as const;
}
