// This file is generated by scripts/openapi-query-options.mjs.
// Source: src/openapi/openapi.yaml (repository root)
// OpenAPI: forklift API 0.1.0

import { queryOptions } from "@tanstack/react-query";

import { type HttpClient } from "@/lib/http/client/http-client";
import { openApiQueryKeys } from "@/query/v1/openapi-query-keys";
import {
  getAnnouncement,
  getMe,
  getStatsLanding,
  getVersion,
} from "@/services/v1/session/api";

export function createSessionOpenApiQueryOptions(client: HttpClient) {
  return {
    getMe: () =>
      queryOptions({
        queryKey: openApiQueryKeys.getMe(),
        queryFn: ({ signal }) =>
          getMe({ signal, client }),
      }),
    getVersion: () =>
      queryOptions({
        queryKey: openApiQueryKeys.getVersion(),
        queryFn: ({ signal }) =>
          getVersion({ signal, client }),
      }),
    getStatsLanding: () =>
      queryOptions({
        queryKey: openApiQueryKeys.getStatsLanding(),
        queryFn: ({ signal }) =>
          getStatsLanding({ signal, client }),
      }),
    getAnnouncement: () =>
      queryOptions({
        queryKey: openApiQueryKeys.getAnnouncement(),
        queryFn: ({ signal }) =>
          getAnnouncement({ signal, client }),
      }),
  } as const;
}
