import { Link, useParams } from "@tanstack/react-router";
import { ArrowDown } from "lucide-react";
import { useQuery } from "@tanstack/react-query";
import { Redirect } from "@/components/app/redirect";
import type { Me } from "@/services/v1/openapi-types";
import { Alert } from "@/components/app-ui/alert";
import { getErrorMessageIfAny } from "@/lib/http/error/api-error";
import { openApiQueryOptions } from "@/query/v1/openapi-query-options";
import { Badge } from "@/components/app-ui/badge";
import { CopyButton } from "@/components/app-ui/copy-button";
import { PageHeader } from "@/components/app-ui/page";
import { UpstreamStatus } from "@/components/feedback/upstream-status";
import { Card, CardContent } from "@/components/ui/card";
import { useLanguage, useTranslation } from "@/lib/i18n";
import { repositoryDescription } from "@/lib/seed-descriptions";
import { cn } from "@/lib/utils";
import { ApprovalList } from "@/routes/workspace/approvals/-components/approval-list";
import { Artifacts } from "@/routes/workspace/repositories/-components/detail/artifacts-tab";
import { AuditLogs } from "@/routes/workspace/repositories/-components/detail/audit-logs-tab";
import { OCIImagesTab } from "@/routes/workspace/repositories/-components/detail/oci-images-tab";
import { RepoPermissions } from "@/routes/workspace/repositories/-components/detail/permissions-tab";
import { Security } from "@/routes/workspace/repositories/-components/detail/security-tab";
import { Settings } from "@/routes/workspace/repositories/-components/detail/settings-tab";
import { Statistics } from "@/routes/workspace/repositories/-components/detail/statistics-tab";
import { canEditRepositorySecurity, canReviewApprovals } from "@/utils/permissions";
import { getRepositoryEndpoint } from "@/utils/repository-endpoint";

export function RepositoryDetail({ me }: { me: Me }) {
  const { t } = useTranslation();
  const language = useLanguage();
  const { id, tab: routeTab } = useParams({ strict: false }) as { id?: string; tab?: string };
  const tab = routeTab ?? "artifacts";
  const repositoryQuery = useQuery({
    ...openApiQueryOptions.getRepository({ path: { id: Number(id) } }),
    enabled: Number.isFinite(Number(id)),
    meta: { suppressGlobalErrorToast: true },
  });
  const repo = repositoryQuery.data;
  const error = getErrorMessageIfAny(repositoryQuery.error);

  // The tabs no longer take a setRepo. Each holds its own edit draft and saves
  // through a mutation that invalidates this query, so a change made on one tab
  // reaches the others without being threaded through here.
  if (!repo) {
    return error
      ? <Alert>{error}</Alert>
      : <div className="text-sm text-muted-foreground">{t("common.loading")}</div>;
  }

  // Tabs follow Nexus-style privileges: every authenticated reader can browse
  // Artifacts; Approvals needs the approve action; Permissions, Audit, Security
  // and Settings are for admins and auditors (auditors see them read-only).
  // Direct URL access to a hidden tab redirects to Artifacts.
  const gated = (repo.type === "proxy" || repo.type === "hosted") && Boolean(repo.config.approval?.enabled);
  const canApprove = canReviewApprovals(me);
  const canAdminView = me.admin || me.auditor;
  const tabs = [
    { key: "artifacts", label: t("common.artifacts") },
    { key: "statistics", label: t("common.statistics") },
    ...((repo.type === "proxy" || repo.type === "hosted") && canApprove ? [{ key: "approvals", label: t("approval.title") }] : []),
    ...(canAdminView ? [{ key: "permissions", label: t("common.permissions") }, { key: "audit", label: "Audit" }, { key: "security", label: t("common.security") }, { key: "settings", label: "Settings" }] : []),
  ];

  if (!tabs.some((t) => t.key === tab)) {
    return <Redirect to="/workspace/repositories/$id/$tab" params={{ id: String(id), tab: "artifacts" }} replace />;
  }

  const endpoint = getRepositoryEndpoint(repo.format, repo.name);

  return (
    <>
      <PageHeader
        title={
          <div className="flex min-w-0 flex-wrap items-center gap-2">
            <span className="min-w-0 truncate">{repo.name}</span>
            <Badge variant="secondary">{repo.type}</Badge>
            <Badge>{repo.format}</Badge>
          </div>
        }
      />
      {repositoryDescription(repo, language) && (
        <p className="mb-4 -mt-2 max-w-[58rem] text-sm leading-relaxed text-muted-foreground">
          {repositoryDescription(repo, language)}
        </p>
      )}

      <Card size="sm" className="mb-4">
        <CardContent>
        <div className="flex items-center gap-2">
          <h2 className="m-0 text-xs font-semibold uppercase tracking-wide text-muted-foreground">{t("repo.client-endpoint")}</h2>
          <span className="text-xs text-muted-foreground">{t("repo.autogenerated-subtitle")}</span>
        </div>
        <div className="mt-2 flex min-w-0 items-stretch gap-2 max-sm:flex-wrap max-sm:flex-col">
          <code className="flex-1 cursor-text select-all overflow-x-auto whitespace-nowrap rounded-[var(--radius)] border border-dashed border-border bg-muted px-2.5 py-2 font-mono text-[13px]">{endpoint.url}</code>
          <CopyButton value={endpoint.url} />
        </div>
        {endpoint.hint && <p className="mt-2 text-sm text-muted-foreground">Configure in: {endpoint.hint}</p>}
        {repo.type === "proxy" && repo.upstream_url && (
          <>
            {/* Connector: on a cache miss the request continues down to the upstream. */}
            <div className="my-1.5 ml-5 flex w-4 flex-col items-center text-muted-foreground" aria-hidden="true">
              <span className="h-3 border-l border-dashed border-border" />
              <ArrowDown className="size-3.5" />
            </div>
            <div className="flex items-center gap-3">
              <h2 className="m-0 text-xs font-semibold uppercase tracking-wide text-muted-foreground">{t("common.upstream")}</h2>
              <UpstreamStatus repoId={repo.id} poll />
            </div>
            <div className="mt-2 flex min-w-0 items-stretch gap-2 max-sm:flex-wrap max-sm:flex-col">
              <code className="flex-1 cursor-text select-all overflow-x-auto whitespace-nowrap rounded-[var(--radius)] border border-dashed border-border bg-muted px-2.5 py-2 font-mono text-[13px]">{repo.upstream_url}</code>
              <CopyButton value={repo.upstream_url} />
            </div>
          </>
        )}
        </CardContent>
      </Card>

      <nav className="mb-[18px] flex gap-1 border-b border-border max-[760px]:overflow-x-auto max-[760px]:pb-px">
        {tabs.map((t) => (
          <Link key={t.key} className={cn("mb-[-1px] rounded-t-[var(--radius)] border border-transparent border-b-0 px-3.5 py-[9px] text-sm text-muted-foreground hover:bg-muted hover:text-foreground hover:no-underline max-[760px]:whitespace-nowrap", tab === t.key && "border-border border-b-card bg-card text-accent-ink")}
            to="/workspace/repositories/$id/$tab" params={{ id: String(id), tab: t.key }}>{t.label}</Link>
        ))}
      </nav>

      {tab === "artifacts" && (repo.format === "oci"
        ? <OCIImagesTab repo={repo} />
        : <Artifacts repo={repo} canDelete={repo.capabilities?.delete ?? !!me.admin} />)}
      {tab === "statistics" && <Statistics repo={repo} />}
      {tab === "permissions" && <RepoPermissions repoId={repo.id} />}
      {tab === "audit" && <AuditLogs repo={repo} />}
      {tab === "approvals" && (repo.type === "proxy" || repo.type === "hosted") && (
        gated && <ApprovalList repo={repo.name} showRepo={false} repoNames={[repo.name]} />
      )}
      {tab === "security" && <Security repo={repo} canWrite={canEditRepositorySecurity(me)} />}
      {tab === "settings" && <Settings repo={repo} canWrite={Boolean(me.admin)} />}
    </>
  );
}

// --- Source-IP ACL helpers: resolve an allow-list entry (a single IP or a CIDR
// block) to its first/last address and how many addresses it spans, so the UI
// can show the range and count a CIDR expands to. IPv4 and pure-hextet IPv6 are
// supported; embedded-IPv4 IPv6 (::ffff:1.2.3.4) is treated as unrecognised. ---
