// This file is generated by scripts/openapi-codegen.mjs.
// Source: src/openapi/openapi.yaml (repository root)
// OpenAPI: forklift API 0.1.0

export type GetHealthzResponse = void;

export type GetReadyzResponse = void;
