{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "argocd-promotion-gate.fullname" . }}
  namespace: {{ .Values.promotionGate.argocd.namespace }}
  labels:
    {{- include "argocd-promotion-gate.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - argoproj.io
    resources:
      - applications
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
      - patch
{{- end }}
