apiVersion: v1
kind: Service
metadata:
  name: {{ include "argocd-promotion-gate.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "argocd-promotion-gate.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  {{- with .Values.service.trafficDistribution }}
  trafficDistribution: {{ . }}
  {{- end }}
  selector:
    {{- include "argocd-promotion-gate.selectorLabels" . | nindent 4 }}
  ports:
    - name: webhook
      port: {{ .Values.service.webhookPort }}
      targetPort: webhook
      protocol: TCP
    - name: admin
      port: {{ .Values.service.adminPort }}
      targetPort: admin
      protocol: TCP
