// This file is generated by scripts/openapi-query-options.mjs.
// Source: src/openapi/openapi.yaml (repository root)
// OpenAPI: forklift API 0.1.0

import { queryOptions } from "@tanstack/react-query";

import { type HttpClient } from "@/lib/http/client/http-client";
import { openApiQueryKeys } from "@/query/v1/openapi-query-keys";
import {
  getHealthz,
  getReadyz,
} from "@/services/v1/system/api";

export function createSystemOpenApiQueryOptions(client: HttpClient) {
  return {
    getHealthz: () =>
      queryOptions({
        queryKey: openApiQueryKeys.getHealthz(),
        queryFn: ({ signal }) =>
          getHealthz({ signal, client }),
      }),
    getReadyz: () =>
      queryOptions({
        queryKey: openApiQueryKeys.getReadyz(),
        queryFn: ({ signal }) =>
          getReadyz({ signal, client }),
      }),
  } as const;
}
