// This file is generated by scripts/openapi-codegen.mjs.
// Source: src/openapi/openapi.yaml (repository root)
// OpenAPI: forklift API 0.1.0

export interface RoleRef { id: number; name: string; }

export interface RoleCreate { name: string; description?: string; permissions?: PermissionCreate[]; }

export interface PermissionCreate { repo_pattern: string; actions: ("read" | "write" | "delete" | "approve" | "audit" | "security" | "admin")[]; }

export interface Permission { id: number; repo_pattern: string; actions: string[]; }

export interface Role { id: number; name: string; description: string; created_at: string; managed: boolean; permissions: Permission[]; user_count: number; }

export interface User { id: number; username: string; source: "local" | "oidc"; email: string; disabled: boolean; robot: boolean; created_at: string; last_login_at: string | null; roles: RoleRef[]; lockout_enabled: boolean; locked: boolean; failed_login_count: number; protected: boolean; token_count: number; }

export interface Token { id: number; name: string; description: string; scopes_json: string; expires_at: string | null; last_used_at: string | null; created_at: string; }

export interface GroupMapping { id: number; group_name: string; role_id: number; managed: boolean; }

export interface Me { authenticated: boolean; username?: string; source?: string; admin?: boolean; approver?: boolean; auditor?: boolean; security?: boolean; csrf_token?: string; impersonator?: string; }

export interface OCITagInfo { path: string; labels: ArtifactLabel[]; can_label: boolean; name: string; tag: string; digest: string; media_type: string; kind: "chart" | "image" | "artifact" | "index"; size: number; platforms: string[]; pushed_at: string; pulled_at: string | null; pushed_by: string; pulled_by: string; }

export interface OCIArtifactDetail { info: OCITagInfo; path: string; labels: ArtifactLabel[]; can_label: boolean; manifest_json: Record<string, unknown>; config_json?: Record<string, unknown>; image?: { os?: string; architecture?: string; created?: string; entrypoint?: string[]; cmd?: string[]; env?: string[]; layers?: number; }; chart?: { values_yaml?: string; readme_md?: string; }; children?: { digest?: string; platform?: string; size?: number; }[]; }

export interface LandingStats { repositories: number; artifacts: number; }

export interface Version { version?: string; commit?: string; oidc_enabled?: boolean; }

export interface Announcement { body: string; updated_by?: string; updated_at: string; }

export interface AnnouncementInput { body: string; }

export interface SearchResult { query?: string; repositories?: { id?: number; name?: string; format?: string; type?: string; }[] | null; artifacts?: { repo_id?: number; repo_name?: string; path?: string; size?: number; }[] | null; labels?: { repo_id?: number; repo_name?: string; path?: string; label?: string; }[] | null; approvals?: ({ id?: number; repo_name?: string; package?: string; status?: "pending" | "approved" | "rejected"; })[] | null; users?: { id?: number; username?: string; robot?: boolean; }[] | null; roles?: { id?: number; name?: string; description?: string; }[] | null; counts?: Record<string, number>; }

export interface Repository { id: number; name: string; format: "maven" | "npm" | "cargo" | "go" | "pypi" | "raw" | "oci"; type: "hosted" | "proxy" | "group"; upstream_url: string; config: RepoConfig; description: string; disabled: boolean; seeded: boolean; created_at: string; updated_at: string; capabilities: RepositoryCapabilities; publish_methods: ("mvn" | "npm" | "twine" | "docker" | "helm" | "oras")[]; }

export type RepositoryListItem = Repository & { artifact_count: number; total_size: number; pending_approval_count: number; can_write: boolean; scanned_count: number; clean_count: number; };

export interface RepositoryCapabilities { read: boolean; write: boolean; delete: boolean; upload: boolean; }

export interface RepositoryCreate { name: string; format: "maven" | "npm" | "cargo" | "go" | "pypi" | "raw" | "oci"; type: "hosted" | "proxy" | "group"; upstream_url?: string; config?: RepoConfig; description?: string; }

export interface RepoConfig { public?: boolean; cache: CacheConfig; age_policy: AgePolicyConfig; approval: ApprovalConfig; policy_pipeline: PolicyPipelineConfig; group: GroupConfig; ip_acl: IPACLConfig; notify: NotifyConfig; retention: RetentionConfig; vuln: VulnPolicyConfig; license: LicensePolicyConfig; upload: UploadConfig; upstream_auth?: UpstreamAuthConfig; }

export interface CacheConfig { enabled: boolean; artifact_ttl: string; metadata_ttl: string; negative_ttl: string; max_size_bytes: number; eviction: "lru"; }

export interface AgePolicyConfig { enabled: boolean; min_age: string; max_age: string; action: "block" | "warn"; }

export interface ApprovalConfig { enabled: boolean; mode?: "enforce" | "audit"; auto_approve?: string[]; auto_approve_clean?: boolean; }

export interface PolicyPipelineConfig { schema_version: 2; order: ("vulnerability" | "license" | "age")[]; }

export interface GroupConfig { members?: string[]; }

export interface IPACLConfig { enabled: boolean; allow?: string[]; }

export interface NotifyConfig { receivers?: string[]; }

export interface RetentionConfig { idle_ttl?: string; }

export interface VulnPolicyConfig { enabled: boolean; threshold?: "critical" | "high" | "medium" | "low"; action?: "block" | "warn" | "audit"; ignore?: string[]; block_unscanned?: boolean; }

export interface LicensePolicyConfig { enabled: boolean; action?: "block" | "warn" | "audit"; deny?: string[]; allow?: string[]; block_unresolved?: boolean; }

export interface UploadConfig { pypi_allow_legacy_zip?: boolean; }

export interface UpstreamAuthConfig { type?: "" | "basic" | "bearer" | "header"; username?: string; password?: string; token?: string; header?: string; value?: string; }

export interface PackageApprovalList { count: number; approvals: PackageApproval[]; }

export interface ApprovalCount { count: number; }

export interface PendingApprovalRepoList { repos: PendingApprovalRepo[]; }

export interface VersionDenyList { count: number; denies: VersionDeny[]; }

export interface PackageApproval { id: number; repo_name: string; package: string; status: "pending" | "approved" | "rejected"; requested_by: string; decided_by: string; note: string; request_count: number; last_requested_version: string; first_requested_at: string; last_requested_at: string; decided_at: string | null; vuln_severity?: string; vuln_ids?: string[]; vuln_scope?: "version" | "package"; vuln_counts?: Record<string, number>; vuln_advisories?: VulnAdvisory[]; vuln_source?: string; vuln_scanned_at?: string | null; vuln_scan_ms?: number; reviewers?: string[]; upstream_url?: string; upstream_package_url?: string; notified_receivers?: string[]; notified_at?: string | null; notify_result?: "delivered" | "failed"; notify_duration_ms?: number; notify_detail?: string; }

export interface VersionDeny { id: number; repo_name: string; package: string; version: string; reason: string; created_by: string; created_at: string; }

export interface AuditLogList { count: number; logs: AuditLog[]; }

export interface AuditLog { id: number; event: "view" | "download" | "upload" | "delete" | "ttl.expire" | "vuln.block" | "license.block" | "repo.create" | "repo.update" | "repo.delete" | "approval.request" | "approval.approve" | "approval.reject" | "deny.create" | "deny.delete" | "deny.block" | "upload.metadata" | "upload.reject" | "upload.cancel"; path: string; username: string; method: string; status: number; client_ip: string; user_agent: string; request_id?: string; detail_json?: string; created_at: string; }

export interface TokenCreate { name: string; description: string; expires_in: string; scopes: TokenScope[]; }

export interface VulnAdvisory { id: string; severity: "critical" | "high" | "medium" | "low"; score?: string; }

export interface PendingApprovalRepo { id: number; repo_name: string; format: string; type: string; pending: number; clean: number; }

export interface IssuedToken { id: number; name: string; description: string; token: string; expires_at: string | null; }

export interface TokenScope { repo_pattern: string; actions: ("read" | "write" | "delete" | "audit")[]; }

export interface HAStatus { enabled: boolean; mode: string; backend: "fs" | "s3"; storage_endpoint?: string; identity: string; leader: string; is_leader: boolean; role: "leader" | "standby"; lease_name?: string; fencing_token?: number; started_at?: string; version?: string; runtime?: string; }

export interface StorageStats { backend: "fs" | "s3"; mode: "filesystem" | "minio" | "s3"; endpoint?: string; bucket?: string; prefix?: string; blob_count: number; blob_bytes: number; minio_error?: string; fs_error?: string; fs?: DiskUsage; dangling: DanglingRef[]; minio?: MinioStats; }

export interface DiskUsage { path?: string; total_bytes: number; used_bytes: number; available_bytes: number; usage_ratio: number; }

export interface DanglingRef { repository: string; repo_id: number; path: string; sha256: string; role?: string; first_seen: string; last_seen: string; hits: number; statuses: StatusCount[]; last_status?: number; }

export interface StatusCount { code: number; count: number; }

export interface MinioStats { total_capacity_bytes: number; used_bytes: number; available_bytes: number; usage_ratio: number; logical_used_bytes: number; object_count: number; bucket_count: number; online_drives: number; offline_drives: number; servers: number; version?: string; }

export interface CoverageProject { id: number; path: string; group: string; name: string; web_url: string; default_branch: string; topics: string[]; applied: "yes" | "partial" | "no" | "error"; branch: string; on_default: boolean | null; format: string; ci_wired: boolean; registry_pinned: boolean; muted_scopes: ("ci" | "registry")[]; evidence: string[]; note: string; skipped: boolean; last_activity_at: string; exclude_reason: string; }

export type CoverageProjectDetail = CoverageProject & { scanned: boolean; };

export interface CoverageExcludedProject { id: number; path: string; group: string; name: string; web_url: string; default_branch: string; topics: string[]; reason: string; last_activity_at: string; }

export interface CoverageProgress { phase: "listing" | "scanning"; done: number; total: number; excluded: number; started_at: string; applied: number; partial: number; not_applied: number; errored: number; skipped: number; }

export interface CoverageOverview { target: number; applied: number; partial: number; not_applied: number; errored: number; skipped: number; excluded: number; percent: number; projects: CoverageProject[]; excluded_projects: CoverageExcludedProject[]; last_scanned_at: string | null; last_scan_duration_ms: number; last_scan_triggered_by: string; last_scan_error: string; scanning: boolean; scan_progress: CoverageProgress | null; gitlab_url: string; forklift_host: string; configured: boolean; enabled: boolean; credentials_present: boolean; scan_cron: string; timezone: string; auto_scan_enabled: boolean; next_run_at: string | null; alarm_configured: boolean; history_retention_days: number; }

export interface CoverageGroup { group: string; target: number; applied: number; partial: number; not_applied: number; percent: number; }

export interface CoverageSnapshot { target: number; applied: number; partial: number; not_applied: number; skipped: number; percent: number; scanned_at: string; }

export interface CoverageLastCommit { ref: string; short_id: string; title: string; author_name: string; committed_at: string; web_url: string; }

export interface CoveragePipelineFile { path: string; content: string; truncated: boolean; matches_forklift: boolean; }

export interface CoveragePipeline { project_path: string; ref: string; files: CoveragePipelineFile[]; }

export interface CoverageMuteInput { muted?: boolean; scopes?: ("ci" | "registry")[]; }

export interface CoverageMute { project_path: string; muted: boolean; scopes: ("ci" | "registry")[]; }

export interface CoverageSettings { forklift_host: string; exclude_topics: string[]; scan_cron: string; timezone: string; auto_scan_enabled: boolean; report_enabled: boolean; receiver: string; skip_when_full_coverage: boolean; max_branches: number; since_days: number; use_search: boolean; updated_by: string; updated_at: string; gitlab_url: string; gitlab_configured: boolean; forklift_host_default: string; next_run_at: string; }

export interface CoverageSettingsInput { forklift_host?: string; exclude_topics?: string[]; scan_cron?: string; timezone?: string; auto_scan_enabled?: boolean; report_enabled?: boolean; receiver?: string; skip_when_full_coverage?: boolean; max_branches?: number; since_days?: number; use_search?: boolean; }

export interface CoverageHostCheckInput { forklift_host: string; }

export interface CoverageHostCheck { host: string; syntax_error: string; resolved: boolean; addresses: string[]; resolve_error: string; latency_ms: number; }

export interface CoverageGitlabCheck { configured: boolean; url: string; reachable: boolean; status: number; version: string; error: string; latency_ms: number; }

export interface CoverageScanStarted { started: boolean; }

export interface CoverageAlarmPayload { text: string; event: string; target: number; applied: number; partial: number; not_applied: number; errored: number; skipped: number; percent: number; projects?: string[]; timestamp: string; }

export interface CoverageAlarmPreview { payload: CoverageAlarmPayload; sample: boolean; receivers: NotificationSampleReceiver[]; }

export interface NotificationSamplePreview { payload: ApprovalAlarmPayload; receivers: NotificationSampleReceiver[]; }

export interface NotificationSampleReceiver { name: string; exists: boolean; enabled: boolean; }

export interface NotificationSampleReport { results: NotificationSampleResult[]; }

export interface NotificationSampleResult { name: string; ok: boolean; error?: string; }

export interface ApprovalAlarmPayload { text: string; event: string; repository: string; package: string; version?: string; requested_by?: string; timestamp: string; count?: number; packages?: string[]; requesters?: string[]; clean_count?: number; dirty_count?: number; max_severity?: string; max_score?: string; top_cve?: string; top_package?: string; }

export interface Receiver { id: number; name: string; description: string; webhook_configured: boolean; enabled: boolean; created_by: string; created_at: string; updated_at: string; repositories: string[] | null; }

export interface ReceiverInput { name: string; description?: string; webhook_url?: string; enabled?: boolean; }

export interface RepositoryName { name: string; format: string; type: "hosted" | "proxy" | "group"; }

export interface Artifact { path: string; version: string; size: number; content_type: string; published_at: string | null; cached_at: string; last_accessed_at: string; cached_by: string; downloads_30d: number; last_accessed_by: string; publication_id?: string; artifact_role?: "primary" | "metadata" | "checksum" | "index"; labels: ArtifactLabel[]; can_label: boolean; max_severity?: string; vuln_ids?: string[]; vuln_counts?: Record<string, number>; vuln_advisories?: VulnAdvisory[]; vuln_source?: string; vuln_scanned_at?: string | null; licenses?: string[]; license_source?: string; license_resolved_at?: string | null; blob_missing?: boolean; blob_missing_since?: string | null; blob_missing_last_seen?: string | null; blob_missing_last_status?: number; blob_missing_statuses?: { code?: number; count?: number; }[]; }

export interface ArtifactList { count: number; total_size: number; filtered: number; artifacts: Artifact[]; publications: ArtifactPublication[]; }

export interface ArtifactLabel { label: string; created_by: string; created_at: string; }

export interface ArtifactLabelList { path: string; labels: ArtifactLabel[]; can_label: boolean; }

export interface ArtifactBulkLabelInput { paths: string[]; label: string; action: "add" | "remove"; }

export interface ArtifactBulkDeleteInput { paths: string[]; }

export interface ArtifactBulkResult { requested: number; succeeded: number; failed: ArtifactBulkFailure[]; }

export interface ArtifactBulkFailure { path: string; error: string; }

export interface ArtifactLabelInput { path: string; label: string; }

export interface ArtifactPublication { id: string; format: "maven" | "npm" | "cargo" | "go" | "pypi"; coordinate: string; package: string; version: string; asset_count: number; total_size: number; broken_assets?: number; actions: ("replace" | "extend" | "delete" | "yank" | "unyank")[]; yanked: boolean; created_by: string; created_at: string; updated_at: string; }

export interface ArtifactUploadManifest { schema_version: 1; format: "maven" | "npm" | "cargo" | "go" | "pypi"; overwrite: boolean; assets: { part: string; extension?: string; classifier?: string; role?: string; }[]; maven?: MavenUploadManifest; npm?: NPMUploadManifest; pypi?: PyPIUploadManifest; cargo?: CargoUploadManifest; go?: GoUploadManifest; }

export interface MavenUploadManifest { group_id: string; artifact_id: string; version: string; generate_pom: boolean; packaging: string; }

export interface NPMUploadManifest { dist_tag?: string; }

export type PyPIUploadManifest = Record<string, unknown>;

export interface CargoUploadManifest { yanked?: boolean; }

export interface GoUploadManifest { module: string; version: string; time?: string; }

export interface UploadedArtifact { path: string; role: "primary" | "metadata" | "checksum" | "index"; size: number; sha256: string; }

export interface ArtifactUploadResult { upload_id: string; repository: string; format: "maven" | "npm" | "cargo" | "go" | "pypi"; coordinate: string; created: UploadedArtifact[]; replaced: UploadedArtifact[]; derived: UploadedArtifact[]; scan_status: "queued" | "deferred" | "disabled"; durability: "local" | "async"; warnings: Record<string, unknown>[]; }

export interface UploadProblem { type: string; title: string; status: number; code: string; detail: string; upload_id?: string; field_errors?: Record<string, string[]>; conflicts?: string[]; conflict_action?: "replace" | "reject"; retryable?: boolean; }

export interface UploadPlan { path: string; package: string; version: string; content_type: string; size: number; approval_required: boolean; exists: boolean; }

export type UploadResult = UploadPlan & { approval_status: "not_required" | "pending" | "approved" | "rejected" | "audit"; };

export interface UpstreamHealth { applicable?: boolean; reachable?: boolean; status?: number; latency_ms?: number; error?: string; }

export interface RepoPermission { role_id: number; role: string; repo_pattern: string; actions: string[]; user_count: number; }

export interface RepoToken { token_id: number; name: string; owner: string; repo_pattern: string; actions: string[]; unscoped: boolean; expires_at: string | null; last_used_at: string | null; }

export interface SessionIdentity { username: string; source: string; }

export interface ImpersonationStart { username: string; source: string; impersonator: string; expires_in: string; }

export interface CreatedUser { id: number; username: string; }

export interface StatusMessage { status: string; }

export interface UploadSession { upload_id: string; state: string; expires_at: string; result?: ArtifactUploadResult; problem?: UploadProblem; }

export interface PublicationLifecycleResult { publication_id: string; coordinate: string; deleted: string[] | null; derived_updated: UploadedArtifact[] | null; derived_deleted: string[] | null; yanked?: boolean; }

export interface ArtifactPurgeResult { deleted: number; }

export interface ArtifactForceDeleteResult { deleted: string; sha256: string; publication_deleted: boolean; publication_coordinate: string; }

export interface BulkApproveResult { approved: number; }

export interface LoginInput { username?: string; password?: string; }

export interface RepositoryInput { upstream_url?: string; config?: RepoConfig; description?: string; }

export interface RepositorySecurityInput { config?: RepoConfig; }

export interface UpstreamCheckInput { url: string; repository_id?: number; auth?: Record<string, unknown>; }

export interface PublicationYankInput { yanked: boolean; }

export interface RepositoryDisabledInput { disabled: boolean; }

export interface UploadValidationInput { path: string; size: number; content_type?: string; }

export interface TokenScopesInput { scopes: TokenScope[]; }

export interface UserCreate { username: string; password?: string; email?: string; role_ids?: number[]; robot?: boolean; }

export interface UserInput { password?: string; disabled?: boolean; lockout_enabled?: boolean; unlock?: boolean; }

export interface ImpersonationInput { reason: string; }

export interface RoleAssignmentCreate { role_id?: number; }

export interface PackageApprovalCreate { repo: string; package: string; status: "approved" | "rejected"; note?: string; }

export interface BulkApproveInput { repo: string; note: string; clean_only?: boolean; }

export interface ApprovalDecisionInput { note?: string; }

export interface VersionDenyCreate { repo: string; package: string; version: string; reason?: string; }

export interface GroupMappingCreate { group_name: string; role_id: number; }

export interface WebhookTestInput { webhook_url: string; name?: string; }
