// This file is generated by scripts/openapi-codegen.mjs.
// Source: src/openapi/openapi.yaml (repository root)
// OpenAPI: forklift API 0.1.0

import {
  buildOpenApiPath,
  resolveOpenApiRequestOptions,
  type OpenApiRequestOptions,
} from "@/services/v1/openapi-runtime";

import { API_PREFIX } from "@/services/paths";

import type {
  CreateGroupMappingsRequest,
  CreateGroupMappingsResponse,
  DeleteGroupMappingRequest,
  DeleteGroupMappingResponse,
  ListGroupMappingsResponse,
} from "./types";

export function listGroupMappings(options?: OpenApiRequestOptions) {
  const { client, requestOptions } = resolveOpenApiRequestOptions(options);

  return client.get<ListGroupMappingsResponse>(
    `${API_PREFIX}/group-mappings`,
    requestOptions,
  );
}

export function createGroupMappings(params: CreateGroupMappingsRequest, options?: OpenApiRequestOptions) {
  const { client, requestOptions } = resolveOpenApiRequestOptions(options);

  return client.post<CreateGroupMappingsResponse, CreateGroupMappingsRequest["body"]>(
    `${API_PREFIX}/group-mappings`,
    params.body,
    requestOptions,
  );
}

export function deleteGroupMapping(params: DeleteGroupMappingRequest, options?: OpenApiRequestOptions) {
  const { client, requestOptions } = resolveOpenApiRequestOptions(options);

  return client.delete<DeleteGroupMappingResponse, unknown>(
    buildOpenApiPath(`${API_PREFIX}/group-mappings/{id}`, params.path),
    undefined,
    requestOptions,
  );
}
