// This file is generated by scripts/openapi-codegen.mjs.
// Source: src/openapi/openapi.yaml (repository root)
// OpenAPI: forklift API 0.1.0

import type {
  GroupMapping,
  GroupMappingCreate
} from "../openapi-types";

export type ListGroupMappingsResponse = GroupMapping[];

export type CreateGroupMappingsRequest = { body: GroupMappingCreate };
export type CreateGroupMappingsResponse = void;

export type DeleteGroupMappingRequest = { path: { id: number } };
export type DeleteGroupMappingResponse = void;
