// This file is generated by scripts/openapi-query-options.mjs.
// Source: src/openapi/openapi.yaml (repository root)
// OpenAPI: forklift API 0.1.0

import { queryOptions } from "@tanstack/react-query";

import { type HttpClient } from "@/lib/http/client/http-client";
import { openApiQueryKeys } from "@/query/v1/openapi-query-keys";
import {
  listGroupMappings,
} from "@/services/v1/group-mappings/api";

export function createGroupMappingsOpenApiQueryOptions(client: HttpClient) {
  return {
    listGroupMappings: () =>
      queryOptions({
        queryKey: openApiQueryKeys.listGroupMappings(),
        queryFn: ({ signal }) =>
          listGroupMappings({ signal, client }),
      }),
  } as const;
}
