// This file is generated by scripts/openapi-codegen.mjs.
// Source: src/openapi/openapi.yaml (repository root)
// OpenAPI: forklift API 0.1.0

import {
  httpClient,
  type HttpClient,
  type RequestOptions,
} from "@/lib/http/client/http-client";

export type OpenApiPathValue = string | number | boolean;
export type OpenApiQueryValue = OpenApiPathValue | null | undefined;
export type OpenApiRequestOptions = RequestOptions & {
  client?: HttpClient;
};

export function resolveOpenApiRequestOptions(
  options?: OpenApiRequestOptions,
) {
  const { client = httpClient, ...requestOptions } = options ?? {};

  return {
    client,
    requestOptions,
  };
}

export function buildOpenApiPath(
  template: string,
  pathParams?: Record<string, OpenApiPathValue>,
) {
  if (!pathParams) return template;
  return template.replace(/\{([^}]+)\}/g, (_, name: string) =>
    encodeURIComponent(String(pathParams[name])),
  );
}

export function appendOpenApiQuery(
  pathname: string,
  query?: Record<string, OpenApiQueryValue>,
) {
  if (!query) return pathname;
  const searchParams = new URLSearchParams();
  for (const [name, value] of Object.entries(query)) {
    if (value === undefined || value === null) continue;
    searchParams.set(name, String(value));
  }
  const queryString = searchParams.toString();
  return queryString ? `${pathname}?${queryString}` : pathname;
}
