// This file is generated by scripts/openapi-codegen.mjs.
// Source: src/openapi/openapi.yaml (repository root)
// OpenAPI: forklift API 0.1.0

import {
  appendOpenApiQuery,
  resolveOpenApiRequestOptions,
  type OpenApiRequestOptions,
} from "@/services/v1/openapi-runtime";

import { API_PREFIX } from "@/services/paths";

import type {
  GetSearchRequest,
  GetSearchResponse,
} from "./types";

export function getSearch(params: GetSearchRequest, options?: OpenApiRequestOptions) {
  const { client, requestOptions } = resolveOpenApiRequestOptions(options);

  return client.get<GetSearchResponse>(
    appendOpenApiQuery(`${API_PREFIX}/search`, params?.query),
    requestOptions,
  );
}
