[tools]
"aqua:grafana/alloy" = "1.20.0"
argo-rollouts = "1.9.0"
"github:younsl/addons" = { version = "0.1.0", version_prefix = "ij/", rename_exe = "ij" }
istioctl = "1.30.3"
node = "24"
packer = "1.16.0"
terragrunt = "1.1.3"

[settings]
minimum_release_age = "7d"
idiomatic_version_file_enable_tools = ["node"]
