// This file is generated by scripts/openapi-codegen.mjs.
// Source: src/openapi/openapi.yaml (repository root)
// OpenAPI: forklift API 0.1.0

import type {
  SearchResult
} from "../openapi-types";

export type GetSearchRequest = { query?: { q: string; limit?: number } };
export type GetSearchResponse = SearchResult;
