// This file is generated by scripts/openapi-query-options.mjs.
// Source: src/openapi/openapi.yaml (repository root)
// OpenAPI: forklift API 0.1.0

import {
  httpClient,
  type HttpClient,
} from "@/lib/http/client/http-client";
import { createApprovalsOpenApiQueryOptions } from "@/query/v1/approvals/options";
import { createCoverageOpenApiQueryOptions } from "@/query/v1/coverage/options";
import { createGroupMappingsOpenApiQueryOptions } from "@/query/v1/group-mappings/options";
import { createHaOpenApiQueryOptions } from "@/query/v1/ha/options";
import { createNotificationOpenApiQueryOptions } from "@/query/v1/notification/options";
import { createRepositoriesOpenApiQueryOptions } from "@/query/v1/repositories/options";
import { createRolesOpenApiQueryOptions } from "@/query/v1/roles/options";
import { createSearchOpenApiQueryOptions } from "@/query/v1/search/options";
import { createSessionOpenApiQueryOptions } from "@/query/v1/session/options";
import { createSystemOpenApiQueryOptions } from "@/query/v1/system/options";
import { createTokensOpenApiQueryOptions } from "@/query/v1/tokens/options";
import { createUsersOpenApiQueryOptions } from "@/query/v1/users/options";

export { openApiQueryKeys } from "@/query/v1/openapi-query-keys";

export function createOpenApiQueryOptions(client: HttpClient) {
  return {
    ...createApprovalsOpenApiQueryOptions(client),
    ...createCoverageOpenApiQueryOptions(client),
    ...createGroupMappingsOpenApiQueryOptions(client),
    ...createHaOpenApiQueryOptions(client),
    ...createNotificationOpenApiQueryOptions(client),
    ...createRepositoriesOpenApiQueryOptions(client),
    ...createRolesOpenApiQueryOptions(client),
    ...createSearchOpenApiQueryOptions(client),
    ...createSessionOpenApiQueryOptions(client),
    ...createSystemOpenApiQueryOptions(client),
    ...createTokensOpenApiQueryOptions(client),
    ...createUsersOpenApiQueryOptions(client),
  } as const;
}

export const openApiQueryOptions = createOpenApiQueryOptions(httpClient);
