// This file is generated by scripts/openapi-query-options.mjs.
// Source: src/openapi/openapi.yaml (repository root)
// OpenAPI: forklift API 0.1.0

import type {
  GetApprovalRequest,
  GetApprovalsCountRequest,
  ListApprovalsRequest,
  ListVersionDeniesRequest,
} from "@/services/v1/approvals/types";
import type {
  GetCoverageProjectLastCommitRequest,
  GetCoverageProjectPipelineRequest,
  GetCoverageProjectRequest,
  ListCoverageHistoryRequest,
} from "@/services/v1/coverage/types";
import type {
  GetRepositoryNotificationSampleRequest,
} from "@/services/v1/notification/types";
import type {
  GetRepositoryDanglingRequest,
  GetRepositoryOciDetailRequest,
  GetRepositoryRequest,
  GetRepositoryUploadsRequest,
  GetRepositoryUpstreamHealthRequest,
  ListRepositoryArtifactsLabelsRequest,
  ListRepositoryArtifactsRequest,
  ListRepositoryAuditLogsRequest,
  ListRepositoryOciTagsRequest,
  ListRepositoryPermissionsRequest,
  ListRepositoryTokensRequest,
} from "@/services/v1/repositories/types";
import type {
  GetSearchRequest,
} from "@/services/v1/search/types";
import type {
  ListUserTokensRequest,
} from "@/services/v1/tokens/types";
export type OpenApiQueryKeyParams = {
  path?: Record<string, string | number | boolean>;
  query?: Record<string, string | number | boolean | null | undefined>;
};

function key(method: string, routePath: string, params?: OpenApiQueryKeyParams) {
  return ["openapi", method, routePath, params ?? {}] as const;
}

export const openApiQueryKeys = {
  getHealthz: () => key("GET", "/healthz"),
  getReadyz: () => key("GET", "/readyz"),
  getMe: () => key("GET", "/api/v1/me"),
  getVersion: () => key("GET", "/api/v1/version"),
  getStatsLanding: () => key("GET", "/api/v1/stats/landing"),
  getAnnouncement: () => key("GET", "/api/v1/announcement"),
  getSearch: (params?: GetSearchRequest) =>
    key("GET", "/api/v1/search", params),
  listRepositories: () => key("GET", "/api/v1/repositories"),
  getRepository: (params: GetRepositoryRequest) =>
    key("GET", "/api/v1/repositories/{id}", params),
  listRepositoryAuditLogs: (params: ListRepositoryAuditLogsRequest) =>
    key("GET", "/api/v1/repositories/{id}/audit-logs", params),
  listRepositoryNames: () => key("GET", "/api/v1/repository-names"),
  listRepositoryOciTags: (params: ListRepositoryOciTagsRequest) =>
    key("GET", "/api/v1/repositories/{id}/oci-tags", params),
  getRepositoryOciDetail: (params: GetRepositoryOciDetailRequest) =>
    key("GET", "/api/v1/repositories/{id}/oci-detail", params),
  listRepositoryArtifacts: (params: ListRepositoryArtifactsRequest) =>
    key("GET", "/api/v1/repositories/{id}/artifacts", params),
  getRepositoryUploads: (params: GetRepositoryUploadsRequest) =>
    key("GET", "/api/v1/repositories/{id}/uploads/{uploadID}", params),
  getRepositoryDangling: (params: GetRepositoryDanglingRequest) =>
    key("GET", "/api/v1/repositories/{id}/dangling", params),
  listRepositoryArtifactsLabels: (params: ListRepositoryArtifactsLabelsRequest) =>
    key("GET", "/api/v1/repositories/{id}/artifacts/labels", params),
  getRepositoryUpstreamHealth: (params: GetRepositoryUpstreamHealthRequest) =>
    key("GET", "/api/v1/repositories/{id}/upstream-health", params),
  listRepositoryPermissions: (params: ListRepositoryPermissionsRequest) =>
    key("GET", "/api/v1/repositories/{id}/permissions", params),
  listRepositoryTokens: (params: ListRepositoryTokensRequest) =>
    key("GET", "/api/v1/repositories/{id}/tokens", params),
  listTokens: () => key("GET", "/api/v1/tokens"),
  listUsers: () => key("GET", "/api/v1/users"),
  listUserTokens: (params: ListUserTokensRequest) =>
    key("GET", "/api/v1/users/{id}/tokens", params),
  listRoles: () => key("GET", "/api/v1/roles"),
  listApprovals: (params?: ListApprovalsRequest) =>
    key("GET", "/api/v1/approvals", params),
  getApprovalsCount: (params?: GetApprovalsCountRequest) =>
    key("GET", "/api/v1/approvals/count", params),
  listApprovalsPendingRepos: () => key("GET", "/api/v1/approvals/pending-repos"),
  getApproval: (params: GetApprovalRequest) =>
    key("GET", "/api/v1/approvals/{id}", params),
  listVersionDenies: (params?: ListVersionDeniesRequest) =>
    key("GET", "/api/v1/version-denies", params),
  listGroupMappings: () => key("GET", "/api/v1/group-mappings"),
  getHa: () => key("GET", "/api/v1/ha"),
  getStorage: () => key("GET", "/api/v1/storage"),
  listNotificationReceivers: () => key("GET", "/api/v1/notification/receivers"),
  getRepositoryNotificationSample: (params: GetRepositoryNotificationSampleRequest) =>
    key("GET", "/api/v1/repositories/{id}/notification/sample", params),
  getCoverage: () => key("GET", "/api/v1/coverage"),
  listCoverageGroups: () => key("GET", "/api/v1/coverage/groups"),
  listCoverageHistory: (params?: ListCoverageHistoryRequest) =>
    key("GET", "/api/v1/coverage/history", params),
  getCoverageProject: (params?: GetCoverageProjectRequest) =>
    key("GET", "/api/v1/coverage/project", params),
  getCoverageProjectLastCommit: (params?: GetCoverageProjectLastCommitRequest) =>
    key("GET", "/api/v1/coverage/project/last-commit", params),
  getCoverageProjectPipeline: (params?: GetCoverageProjectPipelineRequest) =>
    key("GET", "/api/v1/coverage/project/pipeline", params),
  getCoverageSettings: () => key("GET", "/api/v1/coverage/settings"),
  getCoverageGitlabCheck: () => key("GET", "/api/v1/coverage/gitlab-check"),
  getCoverageNotificationPreview: () => key("GET", "/api/v1/coverage/notification/preview"),
} as const;
