// This file is generated by scripts/openapi-codegen.mjs.
// Source: src/openapi/openapi.yaml (repository root)
// OpenAPI: forklift API 0.1.0

import type {
  HAStatus,
  MigrationList,
  MigrationRecord,
  StatusMessage,
  StorageHealth,
  StorageStats
} from "../openapi-types";

export type GetHaResponse = HAStatus;

export type GetStorageResponse = StorageStats;

export type GetStorageHealthResponse = StorageHealth;

export type ListStorageMigrationsResponse = MigrationList;

export type GetStorageMigrationRequest = { path: { id: string } };
export type GetStorageMigrationResponse = MigrationRecord;

export type PostStepDownHaResponse = StatusMessage;
