// This file is generated by scripts/openapi-codegen.mjs.
// Source: src/openapi/openapi.yaml (repository root)
// OpenAPI: forklift API 0.1.0

import type {
  Announcement,
  AnnouncementInput,
  LandingStats,
  LoginInput,
  Me,
  SessionIdentity,
  Version
} from "../openapi-types";

export type PostLoginRequest = { body: LoginInput };
export type PostLoginResponse = SessionIdentity;

export type PostLogoutResponse = void;

export type GetMeResponse = Me;

export type PostStopImpersonateResponse = SessionIdentity;

export type GetVersionResponse = Version;

export type GetStatsLandingResponse = LandingStats;

export type GetAnnouncementResponse = Announcement;

export type UpdateAnnouncementRequest = { body: AnnouncementInput };
export type UpdateAnnouncementResponse = Announcement;
