// This file is generated by scripts/openapi-codegen.mjs.
// Source: src/openapi/openapi.yaml (repository root)
// OpenAPI: forklift API 0.1.0

import type {
  NotificationSamplePreview,
  NotificationSampleReport,
  Receiver,
  ReceiverInput,
  StatusMessage,
  WebhookTestInput
} from "../openapi-types";

export type ListNotificationReceiversResponse = Receiver[];

export type CreateNotificationReceiversRequest = { body: ReceiverInput };
export type CreateNotificationReceiversResponse = Receiver;

export type UpdateNotificationReceiversRequest = { path: { id: number }; body: ReceiverInput };
export type UpdateNotificationReceiversResponse = Receiver;

export type DeleteNotificationReceiversRequest = { path: { id: number } };
export type DeleteNotificationReceiversResponse = void;

export type PostTestNotificationReceiversRequest = { path: { id: number } };
export type PostTestNotificationReceiversResponse = StatusMessage;

export type PostTestNotificationRequest = { body: WebhookTestInput };
export type PostTestNotificationResponse = StatusMessage;

export type GetRepositoryNotificationSampleRequest = { path: { id: number } };
export type GetRepositoryNotificationSampleResponse = NotificationSamplePreview;

export type PostSampleRepositoryNotificationRequest = { path: { id: number } };
export type PostSampleRepositoryNotificationResponse = NotificationSampleReport;
