// This file is generated by scripts/openapi-codegen.mjs.
// Source: src/openapi/openapi.yaml (repository root)
// OpenAPI: forklift API 0.1.0

import type {
  CreatedUser,
  ImpersonationInput,
  ImpersonationStart,
  RoleAssignmentCreate,
  User,
  UserCreate,
  UserInput
} from "../openapi-types";

export type ListUsersResponse = User[];

export type CreateUsersRequest = { body: UserCreate };
export type CreateUsersResponse = CreatedUser;

export type UpdateUserRequest = { path: { id: number }; body: UserInput };
export type UpdateUserResponse = User;

export type DeleteUserRequest = { path: { id: number } };
export type DeleteUserResponse = void;

export type PostImpersonateUserRequest = { path: { id: number }; body: ImpersonationInput };
export type PostImpersonateUserResponse = ImpersonationStart;

export type CreateUserRolesRequest = { path: { id: number }; body: RoleAssignmentCreate };
export type CreateUserRolesResponse = void;

export type DeleteUserRolesRequest = { path: { id: number; roleID: number } };
export type DeleteUserRolesResponse = void;
