// This file is generated by scripts/openapi-codegen.mjs.
// Source: src/openapi/openapi.yaml (repository root)
// OpenAPI: forklift API 0.1.0

import type {
  IssuedToken,
  Token,
  TokenCreate,
  TokenScopesInput
} from "../openapi-types";

export type ListTokensResponse = Token[];

export type CreateTokensRequest = { body: TokenCreate };
export type CreateTokensResponse = IssuedToken;

export type UpdateTokenRequest = { path: { id: number }; body: TokenScopesInput };
export type UpdateTokenResponse = void;

export type DeleteTokenRequest = { path: { id: number } };
export type DeleteTokenResponse = void;

export type ListUserTokensRequest = { path: { id: number } };
export type ListUserTokensResponse = Token[];

export type CreateUserTokensRequest = { path: { id: number }; body: TokenCreate };
export type CreateUserTokensResponse = IssuedToken;

export type UpdateUserTokensRequest = { path: { id: number; tokenID: number }; body: TokenScopesInput };
export type UpdateUserTokensResponse = void;

export type DeleteUserTokensRequest = { path: { id: number; tokenID: number } };
export type DeleteUserTokensResponse = void;
