// This file is generated by scripts/openapi-codegen.mjs.
// Source: src/openapi/openapi.yaml (repository root)
// OpenAPI: forklift API 0.1.0

import type {
  Permission,
  PermissionCreate,
  Role,
  RoleCreate
} from "../openapi-types";

export type ListRolesResponse = Role[];

export type CreateRolesRequest = { body: RoleCreate };
export type CreateRolesResponse = Role;

export type DeleteRoleRequest = { path: { id: number } };
export type DeleteRoleResponse = void;

export type CreateRolePermissionsRequest = { path: { id: number }; body: PermissionCreate };
export type CreateRolePermissionsResponse = Permission;

export type DeleteRolePermissionsRequest = { path: { id: number; permID: number } };
export type DeleteRolePermissionsResponse = void;
