// This file is generated by scripts/openapi-query-options.mjs.
// Source: src/openapi/openapi.yaml (repository root)
// OpenAPI: forklift API 0.1.0

import { queryOptions } from "@tanstack/react-query";

import { type HttpClient } from "@/lib/http/client/http-client";
import { openApiQueryKeys } from "@/query/v1/openapi-query-keys";
import {
  getRepositoryNotificationSample,
  listNotificationReceivers,
} from "@/services/v1/notification/api";
import type {
  GetRepositoryNotificationSampleRequest,
} from "@/services/v1/notification/types";
export function createNotificationOpenApiQueryOptions(client: HttpClient) {
  return {
    listNotificationReceivers: () =>
      queryOptions({
        queryKey: openApiQueryKeys.listNotificationReceivers(),
        queryFn: ({ signal }) =>
          listNotificationReceivers({ signal, client }),
      }),
    getRepositoryNotificationSample: (params: GetRepositoryNotificationSampleRequest) =>
      queryOptions({
        queryKey: openApiQueryKeys.getRepositoryNotificationSample(params),
        queryFn: ({ signal }) =>
          getRepositoryNotificationSample(params, { signal, client }),
      }),
  } as const;
}
