// This file is generated by scripts/openapi-codegen.mjs.
// Source: src/openapi/openapi.yaml (repository root)
// OpenAPI: forklift API 0.1.0

import {
  resolveOpenApiRequestOptions,
  type OpenApiRequestOptions,
} from "@/services/v1/openapi-runtime";

import type {
  GetHealthzResponse,
  GetReadyzResponse,
} from "./types";

export function getHealthz(options?: OpenApiRequestOptions) {
  const { client, requestOptions } = resolveOpenApiRequestOptions(options);

  return client.get<GetHealthzResponse>(
    `/healthz`,
    requestOptions,
  );
}

export function getReadyz(options?: OpenApiRequestOptions) {
  const { client, requestOptions } = resolveOpenApiRequestOptions(options);

  return client.get<GetReadyzResponse>(
    `/readyz`,
    requestOptions,
  );
}
