// This file is generated by scripts/openapi-codegen.mjs.
// Source: src/openapi/openapi.yaml (repository root)
// OpenAPI: forklift API 0.1.0

import {
  resolveOpenApiRequestOptions,
  type OpenApiRequestOptions,
} from "@/services/v1/openapi-runtime";

import { API_PREFIX } from "@/services/paths";

import type {
  GetAnnouncementResponse,
  GetMeResponse,
  GetStatsLandingResponse,
  GetVersionResponse,
  PostLoginRequest,
  PostLoginResponse,
  PostLogoutResponse,
  PostStopImpersonateResponse,
  UpdateAnnouncementRequest,
  UpdateAnnouncementResponse,
} from "./types";

export function postLogin(params: PostLoginRequest, options?: OpenApiRequestOptions) {
  const { client, requestOptions } = resolveOpenApiRequestOptions(options);

  return client.post<PostLoginResponse, PostLoginRequest["body"]>(
    `${API_PREFIX}/login`,
    params.body,
    requestOptions,
  );
}

export function postLogout(options?: OpenApiRequestOptions) {
  const { client, requestOptions } = resolveOpenApiRequestOptions(options);

  return client.post<PostLogoutResponse, unknown>(
    `${API_PREFIX}/logout`,
    undefined,
    requestOptions,
  );
}

export function getMe(options?: OpenApiRequestOptions) {
  const { client, requestOptions } = resolveOpenApiRequestOptions(options);

  return client.get<GetMeResponse>(
    `${API_PREFIX}/me`,
    requestOptions,
  );
}

export function postStopImpersonate(options?: OpenApiRequestOptions) {
  const { client, requestOptions } = resolveOpenApiRequestOptions(options);

  return client.post<PostStopImpersonateResponse, unknown>(
    `${API_PREFIX}/impersonate/stop`,
    undefined,
    requestOptions,
  );
}

export function getVersion(options?: OpenApiRequestOptions) {
  const { client, requestOptions } = resolveOpenApiRequestOptions(options);

  return client.get<GetVersionResponse>(
    `${API_PREFIX}/version`,
    requestOptions,
  );
}

export function getStatsLanding(options?: OpenApiRequestOptions) {
  const { client, requestOptions } = resolveOpenApiRequestOptions(options);

  return client.get<GetStatsLandingResponse>(
    `${API_PREFIX}/stats/landing`,
    requestOptions,
  );
}

export function getAnnouncement(options?: OpenApiRequestOptions) {
  const { client, requestOptions } = resolveOpenApiRequestOptions(options);

  return client.get<GetAnnouncementResponse>(
    `${API_PREFIX}/announcement`,
    requestOptions,
  );
}

export function updateAnnouncement(params: UpdateAnnouncementRequest, options?: OpenApiRequestOptions) {
  const { client, requestOptions } = resolveOpenApiRequestOptions(options);

  return client.put<UpdateAnnouncementResponse, UpdateAnnouncementRequest["body"]>(
    `${API_PREFIX}/announcement`,
    params.body,
    requestOptions,
  );
}
