// This file is generated by scripts/openapi-query-options.mjs.
// Source: src/openapi/openapi.yaml (repository root)
// OpenAPI: forklift API 0.1.0

import { queryOptions } from "@tanstack/react-query";

import { type HttpClient } from "@/lib/http/client/http-client";
import { openApiQueryKeys } from "@/query/v1/openapi-query-keys";
import {
  getApproval,
  getApprovalsCount,
  listApprovals,
  listApprovalsPendingRepos,
  listVersionDenies,
} from "@/services/v1/approvals/api";
import type {
  GetApprovalRequest,
  GetApprovalsCountRequest,
  ListApprovalsRequest,
  ListVersionDeniesRequest,
} from "@/services/v1/approvals/types";
export function createApprovalsOpenApiQueryOptions(client: HttpClient) {
  return {
    listApprovals: (params?: ListApprovalsRequest) =>
      queryOptions({
        queryKey: openApiQueryKeys.listApprovals(params),
        queryFn: ({ signal }) =>
          listApprovals(params ?? {}, { signal, client }),
      }),
    getApprovalsCount: (params?: GetApprovalsCountRequest) =>
      queryOptions({
        queryKey: openApiQueryKeys.getApprovalsCount(params),
        queryFn: ({ signal }) =>
          getApprovalsCount(params ?? {}, { signal, client }),
      }),
    listApprovalsPendingRepos: () =>
      queryOptions({
        queryKey: openApiQueryKeys.listApprovalsPendingRepos(),
        queryFn: ({ signal }) =>
          listApprovalsPendingRepos({ signal, client }),
      }),
    getApproval: (params: GetApprovalRequest) =>
      queryOptions({
        queryKey: openApiQueryKeys.getApproval(params),
        queryFn: ({ signal }) =>
          getApproval(params, { signal, client }),
      }),
    listVersionDenies: (params?: ListVersionDeniesRequest) =>
      queryOptions({
        queryKey: openApiQueryKeys.listVersionDenies(params),
        queryFn: ({ signal }) =>
          listVersionDenies(params ?? {}, { signal, client }),
      }),
  } as const;
}
