// This file is generated by scripts/openapi-query-options.mjs.
// Source: src/openapi/openapi.yaml (repository root)
// OpenAPI: forklift API 0.1.0

import { queryOptions } from "@tanstack/react-query";

import { type HttpClient } from "@/lib/http/client/http-client";
import { openApiQueryKeys } from "@/query/v1/openapi-query-keys";
import {
  getHa,
  getStorage,
} from "@/services/v1/ha/api";

export function createHaOpenApiQueryOptions(client: HttpClient) {
  return {
    getHa: () =>
      queryOptions({
        queryKey: openApiQueryKeys.getHa(),
        queryFn: ({ signal }) =>
          getHa({ signal, client }),
      }),
    getStorage: () =>
      queryOptions({
        queryKey: openApiQueryKeys.getStorage(),
        queryFn: ({ signal }) =>
          getStorage({ signal, client }),
      }),
  } as const;
}
