{{- if .Values.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "argocd-canary-gate.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "argocd-canary-gate.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  {{- with .Values.podDisruptionBudget.unhealthyPodEvictionPolicy }}
  unhealthyPodEvictionPolicy: {{ . }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "argocd-canary-gate.selectorLabels" . | nindent 6 }}
{{- end }}
