{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "argocd-canary-gate.fullname" . }}
  namespace: {{ .Values.canaryGate.argocd.namespace }}
  labels:
    {{- include "argocd-canary-gate.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "argocd-canary-gate.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "argocd-canary-gate.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
