// This file is generated by scripts/openapi-query-options.mjs.
// Source: src/openapi/openapi.yaml (repository root)
// OpenAPI: forklift API 0.1.0

import { queryOptions } from "@tanstack/react-query";

import { type HttpClient } from "@/lib/http/client/http-client";
import { openApiQueryKeys } from "@/query/v1/openapi-query-keys";
import {
  getSearch,
} from "@/services/v1/search/api";
import type {
  GetSearchRequest,
} from "@/services/v1/search/types";
export function createSearchOpenApiQueryOptions(client: HttpClient) {
  return {
    getSearch: (params?: GetSearchRequest) =>
      queryOptions({
        queryKey: openApiQueryKeys.getSearch(params),
        queryFn: ({ signal }) =>
          getSearch(params ?? {}, { signal, client }),
      }),
  } as const;
}
