// This file is generated by scripts/openapi-codegen.mjs.
// Source: src/openapi/openapi.yaml (repository root)
// OpenAPI: forklift API 0.1.0

import {
  buildOpenApiPath,
  resolveOpenApiRequestOptions,
  type OpenApiRequestOptions,
} from "@/services/v1/openapi-runtime";

import { API_PREFIX } from "@/services/paths";

import type {
  GetHaResponse,
  GetStorageMigrationRequest,
  GetStorageMigrationResponse,
  GetStorageResponse,
  ListStorageMigrationsResponse,
  PostStepDownHaResponse,
} from "./types";

export function getHa(options?: OpenApiRequestOptions) {
  const { client, requestOptions } = resolveOpenApiRequestOptions(options);

  return client.get<GetHaResponse>(
    `${API_PREFIX}/ha`,
    requestOptions,
  );
}

export function getStorage(options?: OpenApiRequestOptions) {
  const { client, requestOptions } = resolveOpenApiRequestOptions(options);

  return client.get<GetStorageResponse>(
    `${API_PREFIX}/storage`,
    requestOptions,
  );
}

export function listStorageMigrations(options?: OpenApiRequestOptions) {
  const { client, requestOptions } = resolveOpenApiRequestOptions(options);

  return client.get<ListStorageMigrationsResponse>(
    `${API_PREFIX}/storage/migrations`,
    requestOptions,
  );
}

export function getStorageMigration(params: GetStorageMigrationRequest, options?: OpenApiRequestOptions) {
  const { client, requestOptions } = resolveOpenApiRequestOptions(options);

  return client.get<GetStorageMigrationResponse>(
    buildOpenApiPath(`${API_PREFIX}/storage/migrations/{id}`, params.path),
    requestOptions,
  );
}

export function postStepDownHa(options?: OpenApiRequestOptions) {
  const { client, requestOptions } = resolveOpenApiRequestOptions(options);

  return client.post<PostStepDownHaResponse, unknown>(
    `${API_PREFIX}/ha/step-down`,
    undefined,
    requestOptions,
  );
}
