// This file is generated by scripts/openapi-codegen.mjs.
// Source: src/openapi/openapi.yaml (repository root)
// OpenAPI: forklift API 0.1.0

import {
  resolveOpenApiRequestOptions,
  type OpenApiRequestOptions,
} from "@/services/v1/openapi-runtime";

import { API_PREFIX } from "@/services/paths";

import type {
  GetHaResponse,
  GetStorageResponse,
  PostStepDownHaResponse,
} from "./types";

export function getHa(options?: OpenApiRequestOptions) {
  const { client, requestOptions } = resolveOpenApiRequestOptions(options);

  return client.get<GetHaResponse>(
    `${API_PREFIX}/ha`,
    requestOptions,
  );
}

export function getStorage(options?: OpenApiRequestOptions) {
  const { client, requestOptions } = resolveOpenApiRequestOptions(options);

  return client.get<GetStorageResponse>(
    `${API_PREFIX}/storage`,
    requestOptions,
  );
}

export function postStepDownHa(options?: OpenApiRequestOptions) {
  const { client, requestOptions } = resolveOpenApiRequestOptions(options);

  return client.post<PostStepDownHaResponse, unknown>(
    `${API_PREFIX}/ha/step-down`,
    undefined,
    requestOptions,
  );
}
