// This file is generated by scripts/openapi-codegen.mjs.
// Source: src/openapi/openapi.yaml (repository root)
// OpenAPI: forklift API 0.1.0

import type {
  HAStatus,
  StatusMessage,
  StorageStats
} from "../openapi-types";

export type GetHaResponse = HAStatus;

export type GetStorageResponse = StorageStats;

export type PostStepDownHaResponse = StatusMessage;
