//! Embedded SQL migrations, applied in file-name order by `Store::open`.
//! Published migrations remain immutable so existing databases open unchanged.

/// (file name, SQL body) pairs sorted by name; names look like `0001_init.sql`.
pub(crate) const MIGRATIONS: &[(&str, &str)] = &[
    ("0001_init.sql", include_str!("migrations/0001_init.sql")),
    (
        "0002_audit_logs.sql",
        include_str!("migrations/0002_audit_logs.sql"),
    ),
    (
        "0003_hosted_type.sql",
        include_str!("migrations/0003_hosted_type.sql"),
    ),
    (
        "0004_user_last_login.sql",
        include_str!("migrations/0004_user_last_login.sql"),
    ),
    (
        "0005_token_description.sql",
        include_str!("migrations/0005_token_description.sql"),
    ),
    (
        "0006_package_approvals.sql",
        include_str!("migrations/0006_package_approvals.sql"),
    ),
    (
        "0007_version_denies.sql",
        include_str!("migrations/0007_version_denies.sql"),
    ),
    (
        "0008_declarative_rbac.sql",
        include_str!("migrations/0008_declarative_rbac.sql"),
    ),
    (
        "0009_approval_requested_version.sql",
        include_str!("migrations/0009_approval_requested_version.sql"),
    ),
    (
        "0010_user_lockout.sql",
        include_str!("migrations/0010_user_lockout.sql"),
    ),
    (
        "0011_vuln_scans.sql",
        include_str!("migrations/0011_vuln_scans.sql"),
    ),
    (
        "0012_repository_disabled.sql",
        include_str!("migrations/0012_repository_disabled.sql"),
    ),
    (
        "0013_vuln_severity_counts.sql",
        include_str!("migrations/0013_vuln_severity_counts.sql"),
    ),
    (
        "0014_vuln_scan_duration.sql",
        include_str!("migrations/0014_vuln_scan_duration.sql"),
    ),
    (
        "0015_vuln_advisories.sql",
        include_str!("migrations/0015_vuln_advisories.sql"),
    ),
    (
        "0016_vuln_source.sql",
        include_str!("migrations/0016_vuln_source.sql"),
    ),
    (
        "0017_license_scans.sql",
        include_str!("migrations/0017_license_scans.sql"),
    ),
    (
        "0018_notification_receivers.sql",
        include_str!("migrations/0018_notification_receivers.sql"),
    ),
    (
        "0019_artifact_cached_by.sql",
        include_str!("migrations/0019_artifact_cached_by.sql"),
    ),
    (
        "0020_approval_notified.sql",
        include_str!("migrations/0020_approval_notified.sql"),
    ),
    (
        "0021_user_robot.sql",
        include_str!("migrations/0021_user_robot.sql"),
    ),
    (
        "0022_approval_notify_result.sql",
        include_str!("migrations/0022_approval_notify_result.sql"),
    ),
    (
        "0023_approval_notify_detail.sql",
        include_str!("migrations/0023_approval_notify_detail.sql"),
    ),
    (
        "0024_artifact_publications.sql",
        include_str!("migrations/0024_artifact_publications.sql"),
    ),
    (
        "0025_artifact_upload_requests.sql",
        include_str!("migrations/0025_artifact_upload_requests.sql"),
    ),
    (
        "0026_audit_request_detail.sql",
        include_str!("migrations/0026_audit_request_detail.sql"),
    ),
    (
        "0027_group_metadata_cache.sql",
        include_str!("migrations/0027_group_metadata_cache.sql"),
    ),
    (
        "0028_blob_gc_grace.sql",
        include_str!("migrations/0028_blob_gc_grace.sql"),
    ),
    (
        "0029_announcement.sql",
        include_str!("migrations/0029_announcement.sql"),
    ),
    (
        "0030_oci_tags.sql",
        include_str!("migrations/0030_oci_tags.sql"),
    ),
    (
        "0031_oci_upload_sessions.sql",
        include_str!("migrations/0031_oci_upload_sessions.sql"),
    ),
    (
        "0032_repository_description.sql",
        include_str!("migrations/0032_repository_description.sql"),
    ),
    (
        "0033_artifact_last_accessed_by.sql",
        include_str!("migrations/0033_artifact_last_accessed_by.sql"),
    ),
    (
        "0034_artifact_labels.sql",
        include_str!("migrations/0034_artifact_labels.sql"),
    ),
    (
        "0035_aggregate_indexes.sql",
        include_str!("migrations/0035_aggregate_indexes.sql"),
    ),
    (
        "0036_coverage.sql",
        include_str!("migrations/0036_coverage.sql"),
    ),
    (
        "0037_coverage_report_enabled.sql",
        include_str!("migrations/0037_coverage_report_enabled.sql"),
    ),
    (
        "0038_coverage_mute_scopes.sql",
        include_str!("migrations/0038_coverage_mute_scopes.sql"),
    ),
    (
        "0039_artifact_download_counts.sql",
        include_str!("migrations/0039_artifact_download_counts.sql"),
    ),
];
