// This file is generated by scripts/openapi-codegen.mjs.
// Source: src/openapi/openapi.yaml (repository root)
// OpenAPI: forklift API 0.1.0

import {
  buildOpenApiPath,
  resolveOpenApiRequestOptions,
  type OpenApiRequestOptions,
} from "@/services/v1/openapi-runtime";

import { API_PREFIX } from "@/services/paths";

import type {
  CreateRolePermissionsRequest,
  CreateRolePermissionsResponse,
  CreateRolesRequest,
  CreateRolesResponse,
  DeleteRolePermissionsRequest,
  DeleteRolePermissionsResponse,
  DeleteRoleRequest,
  DeleteRoleResponse,
  ListRolesResponse,
} from "./types";

export function listRoles(options?: OpenApiRequestOptions) {
  const { client, requestOptions } = resolveOpenApiRequestOptions(options);

  return client.get<ListRolesResponse>(
    `${API_PREFIX}/roles`,
    requestOptions,
  );
}

export function createRoles(params: CreateRolesRequest, options?: OpenApiRequestOptions) {
  const { client, requestOptions } = resolveOpenApiRequestOptions(options);

  return client.post<CreateRolesResponse, CreateRolesRequest["body"]>(
    `${API_PREFIX}/roles`,
    params.body,
    requestOptions,
  );
}

export function deleteRole(params: DeleteRoleRequest, options?: OpenApiRequestOptions) {
  const { client, requestOptions } = resolveOpenApiRequestOptions(options);

  return client.delete<DeleteRoleResponse, unknown>(
    buildOpenApiPath(`${API_PREFIX}/roles/{id}`, params.path),
    undefined,
    requestOptions,
  );
}

export function createRolePermissions(params: CreateRolePermissionsRequest, options?: OpenApiRequestOptions) {
  const { client, requestOptions } = resolveOpenApiRequestOptions(options);

  return client.post<CreateRolePermissionsResponse, CreateRolePermissionsRequest["body"]>(
    buildOpenApiPath(`${API_PREFIX}/roles/{id}/permissions`, params.path),
    params.body,
    requestOptions,
  );
}

export function deleteRolePermissions(params: DeleteRolePermissionsRequest, options?: OpenApiRequestOptions) {
  const { client, requestOptions } = resolveOpenApiRequestOptions(options);

  return client.delete<DeleteRolePermissionsResponse, unknown>(
    buildOpenApiPath(`${API_PREFIX}/roles/{id}/permissions/{permID}`, params.path),
    undefined,
    requestOptions,
  );
}
