// This file is generated by scripts/openapi-codegen.mjs.
// Source: src/openapi/openapi.yaml (repository root)
// OpenAPI: forklift API 0.1.0

import {
  appendOpenApiQuery,
  buildOpenApiPath,
  resolveOpenApiRequestOptions,
  type OpenApiRequestOptions,
} from "@/services/v1/openapi-runtime";

import { API_PREFIX } from "@/services/paths";

import type {
  CreateApprovalsRequest,
  CreateApprovalsResponse,
  CreateVersionDeniesRequest,
  CreateVersionDeniesResponse,
  DeleteVersionDenyRequest,
  DeleteVersionDenyResponse,
  GetApprovalRequest,
  GetApprovalResponse,
  GetApprovalsCountRequest,
  GetApprovalsCountResponse,
  ListApprovalsPendingReposResponse,
  ListApprovalsRequest,
  ListApprovalsResponse,
  ListVersionDeniesRequest,
  ListVersionDeniesResponse,
  PostApproveAllApprovalsRequest,
  PostApproveAllApprovalsResponse,
  PostApproveApprovalRequest,
  PostApproveApprovalResponse,
  PostRejectApprovalRequest,
  PostRejectApprovalResponse,
} from "./types";

export function listApprovals(params: ListApprovalsRequest, options?: OpenApiRequestOptions) {
  const { client, requestOptions } = resolveOpenApiRequestOptions(options);

  return client.get<ListApprovalsResponse>(
    appendOpenApiQuery(`${API_PREFIX}/approvals`, params?.query),
    requestOptions,
  );
}

export function createApprovals(params: CreateApprovalsRequest, options?: OpenApiRequestOptions) {
  const { client, requestOptions } = resolveOpenApiRequestOptions(options);

  return client.post<CreateApprovalsResponse, CreateApprovalsRequest["body"]>(
    `${API_PREFIX}/approvals`,
    params.body,
    requestOptions,
  );
}

export function getApprovalsCount(params: GetApprovalsCountRequest, options?: OpenApiRequestOptions) {
  const { client, requestOptions } = resolveOpenApiRequestOptions(options);

  return client.get<GetApprovalsCountResponse>(
    appendOpenApiQuery(`${API_PREFIX}/approvals/count`, params?.query),
    requestOptions,
  );
}

export function listApprovalsPendingRepos(options?: OpenApiRequestOptions) {
  const { client, requestOptions } = resolveOpenApiRequestOptions(options);

  return client.get<ListApprovalsPendingReposResponse>(
    `${API_PREFIX}/approvals/pending-repos`,
    requestOptions,
  );
}

export function postApproveAllApprovals(params: PostApproveAllApprovalsRequest, options?: OpenApiRequestOptions) {
  const { client, requestOptions } = resolveOpenApiRequestOptions(options);

  return client.post<PostApproveAllApprovalsResponse, PostApproveAllApprovalsRequest["body"]>(
    `${API_PREFIX}/approvals/approve-all`,
    params.body,
    requestOptions,
  );
}

export function getApproval(params: GetApprovalRequest, options?: OpenApiRequestOptions) {
  const { client, requestOptions } = resolveOpenApiRequestOptions(options);

  return client.get<GetApprovalResponse>(
    buildOpenApiPath(`${API_PREFIX}/approvals/{id}`, params.path),
    requestOptions,
  );
}

export function postApproveApproval(params: PostApproveApprovalRequest, options?: OpenApiRequestOptions) {
  const { client, requestOptions } = resolveOpenApiRequestOptions(options);

  return client.post<PostApproveApprovalResponse, PostApproveApprovalRequest["body"]>(
    buildOpenApiPath(`${API_PREFIX}/approvals/{id}/approve`, params.path),
    params.body,
    requestOptions,
  );
}

export function postRejectApproval(params: PostRejectApprovalRequest, options?: OpenApiRequestOptions) {
  const { client, requestOptions } = resolveOpenApiRequestOptions(options);

  return client.post<PostRejectApprovalResponse, PostRejectApprovalRequest["body"]>(
    buildOpenApiPath(`${API_PREFIX}/approvals/{id}/reject`, params.path),
    params.body,
    requestOptions,
  );
}

export function listVersionDenies(params: ListVersionDeniesRequest, options?: OpenApiRequestOptions) {
  const { client, requestOptions } = resolveOpenApiRequestOptions(options);

  return client.get<ListVersionDeniesResponse>(
    appendOpenApiQuery(`${API_PREFIX}/version-denies`, params?.query),
    requestOptions,
  );
}

export function createVersionDenies(params: CreateVersionDeniesRequest, options?: OpenApiRequestOptions) {
  const { client, requestOptions } = resolveOpenApiRequestOptions(options);

  return client.post<CreateVersionDeniesResponse, CreateVersionDeniesRequest["body"]>(
    `${API_PREFIX}/version-denies`,
    params.body,
    requestOptions,
  );
}

export function deleteVersionDeny(params: DeleteVersionDenyRequest, options?: OpenApiRequestOptions) {
  const { client, requestOptions } = resolveOpenApiRequestOptions(options);

  return client.delete<DeleteVersionDenyResponse, unknown>(
    buildOpenApiPath(`${API_PREFIX}/version-denies/{id}`, params.path),
    undefined,
    requestOptions,
  );
}
