// This file is generated by scripts/openapi-codegen.mjs.
// Source: src/openapi/openapi.yaml (repository root)
// OpenAPI: forklift API 0.1.0

import type {
  ApprovalCount,
  ApprovalDecisionInput,
  BulkApproveInput,
  BulkApproveResult,
  PackageApproval,
  PackageApprovalCreate,
  PackageApprovalList,
  PendingApprovalRepoList,
  VersionDeny,
  VersionDenyCreate,
  VersionDenyList
} from "../openapi-types";

export type ListApprovalsRequest = { query?: { repo?: string; status?: "pending" | "approved" | "rejected"; q?: string; regex?: boolean; limit?: number; offset?: number } };
export type ListApprovalsResponse = PackageApprovalList;

export type CreateApprovalsRequest = { body: PackageApprovalCreate };
export type CreateApprovalsResponse = PackageApproval;

export type GetApprovalsCountRequest = { query?: { repo?: string; status?: "pending" | "approved" | "rejected" } };
export type GetApprovalsCountResponse = ApprovalCount;

export type ListApprovalsPendingReposResponse = PendingApprovalRepoList;

export type PostApproveAllApprovalsRequest = { body: BulkApproveInput };
export type PostApproveAllApprovalsResponse = BulkApproveResult;

export type GetApprovalRequest = { path: { id: number } };
export type GetApprovalResponse = PackageApproval;

export type PostApproveApprovalRequest = { path: { id: number }; body: ApprovalDecisionInput };
export type PostApproveApprovalResponse = PackageApproval;

export type PostRejectApprovalRequest = { path: { id: number }; body: ApprovalDecisionInput };
export type PostRejectApprovalResponse = PackageApproval;

export type ListVersionDeniesRequest = { query?: { repo?: string; limit?: number; offset?: number } };
export type ListVersionDeniesResponse = VersionDenyList;

export type CreateVersionDeniesRequest = { body: VersionDenyCreate };
export type CreateVersionDeniesResponse = VersionDeny;

export type DeleteVersionDenyRequest = { path: { id: number } };
export type DeleteVersionDenyResponse = void;
