// This file is generated by scripts/openapi-codegen.mjs.
// Source: src/openapi/openapi.yaml (repository root)
// OpenAPI: forklift API 0.1.0

import {
  appendOpenApiQuery,
  buildOpenApiPath,
  resolveOpenApiRequestOptions,
  type OpenApiRequestOptions,
} from "@/services/v1/openapi-runtime";

import { API_PREFIX } from "@/services/paths";

import type {
  CreateRepositoriesRequest,
  CreateRepositoriesResponse,
  CreateRepositoryArtifactsLabelsRequest,
  CreateRepositoryArtifactsLabelsResponse,
  CreateRepositoryUploadsRequest,
  CreateRepositoryUploadsResponse,
  DeleteRepositoryArtifactsLabelsRequest,
  DeleteRepositoryArtifactsLabelsResponse,
  DeleteRepositoryArtifactsRequest,
  DeleteRepositoryArtifactsResponse,
  DeleteRepositoryPublicationsRequest,
  DeleteRepositoryPublicationsResponse,
  DeleteRepositoryRequest,
  DeleteRepositoryResponse,
  DeleteRepositoryUploadsRequest,
  DeleteRepositoryUploadsResponse,
  GetRepositoryDanglingRequest,
  GetRepositoryDanglingResponse,
  GetRepositoryOciDetailRequest,
  GetRepositoryOciDetailResponse,
  GetRepositoryRequest,
  GetRepositoryResponse,
  GetRepositoryUploadsRequest,
  GetRepositoryUploadsResponse,
  GetRepositoryUpstreamHealthRequest,
  GetRepositoryUpstreamHealthResponse,
  ListRepositoriesResponse,
  ListRepositoryArtifactsLabelsRequest,
  ListRepositoryArtifactsLabelsResponse,
  ListRepositoryArtifactsRequest,
  ListRepositoryArtifactsResponse,
  ListRepositoryAuditLogsRequest,
  ListRepositoryAuditLogsResponse,
  ListRepositoryNamesResponse,
  ListRepositoryOciTagsRequest,
  ListRepositoryOciTagsResponse,
  ListRepositoryPermissionsRequest,
  ListRepositoryPermissionsResponse,
  ListRepositoryTokensRequest,
  ListRepositoryTokensResponse,
  PostBulkDeleteRepositoryArtifactsRequest,
  PostBulkDeleteRepositoryArtifactsResponse,
  PostBulkRepositoryArtifactsLabelsRequest,
  PostBulkRepositoryArtifactsLabelsResponse,
  PostCheckUpstreamRepositoriesRequest,
  PostCheckUpstreamRepositoriesResponse,
  PostCommitRepositoryUploadsRequest,
  PostCommitRepositoryUploadsResponse,
  PostDisabledRepositoryRequest,
  PostDisabledRepositoryResponse,
  PostValidateUploadRepositoryArtifactsRequest,
  PostValidateUploadRepositoryArtifactsResponse,
  PostYankRepositoryPublicationsRequest,
  PostYankRepositoryPublicationsResponse,
  UpdateRepositoryArtifactsUploadRequest,
  UpdateRepositoryArtifactsUploadResponse,
  UpdateRepositoryRequest,
  UpdateRepositoryResponse,
  UpdateRepositorySecurityRequest,
  UpdateRepositorySecurityResponse,
} from "./types";

export function listRepositories(options?: OpenApiRequestOptions) {
  const { client, requestOptions } = resolveOpenApiRequestOptions(options);

  return client.get<ListRepositoriesResponse>(
    `${API_PREFIX}/repositories`,
    requestOptions,
  );
}

export function createRepositories(params: CreateRepositoriesRequest, options?: OpenApiRequestOptions) {
  const { client, requestOptions } = resolveOpenApiRequestOptions(options);

  return client.post<CreateRepositoriesResponse, CreateRepositoriesRequest["body"]>(
    `${API_PREFIX}/repositories`,
    params.body,
    requestOptions,
  );
}

export function getRepository(params: GetRepositoryRequest, options?: OpenApiRequestOptions) {
  const { client, requestOptions } = resolveOpenApiRequestOptions(options);

  return client.get<GetRepositoryResponse>(
    buildOpenApiPath(`${API_PREFIX}/repositories/{id}`, params.path),
    requestOptions,
  );
}

export function updateRepository(params: UpdateRepositoryRequest, options?: OpenApiRequestOptions) {
  const { client, requestOptions } = resolveOpenApiRequestOptions(options);

  return client.put<UpdateRepositoryResponse, UpdateRepositoryRequest["body"]>(
    buildOpenApiPath(`${API_PREFIX}/repositories/{id}`, params.path),
    params.body,
    requestOptions,
  );
}

export function deleteRepository(params: DeleteRepositoryRequest, options?: OpenApiRequestOptions) {
  const { client, requestOptions } = resolveOpenApiRequestOptions(options);

  return client.delete<DeleteRepositoryResponse, unknown>(
    buildOpenApiPath(`${API_PREFIX}/repositories/{id}`, params.path),
    undefined,
    requestOptions,
  );
}

export function updateRepositorySecurity(params: UpdateRepositorySecurityRequest, options?: OpenApiRequestOptions) {
  const { client, requestOptions } = resolveOpenApiRequestOptions(options);

  return client.put<UpdateRepositorySecurityResponse, UpdateRepositorySecurityRequest["body"]>(
    buildOpenApiPath(`${API_PREFIX}/repositories/{id}/security`, params.path),
    params.body,
    requestOptions,
  );
}

export function listRepositoryAuditLogs(params: ListRepositoryAuditLogsRequest, options?: OpenApiRequestOptions) {
  const { client, requestOptions } = resolveOpenApiRequestOptions(options);

  return client.get<ListRepositoryAuditLogsResponse>(
    appendOpenApiQuery(buildOpenApiPath(`${API_PREFIX}/repositories/{id}/audit-logs`, params.path), params?.query),
    requestOptions,
  );
}

export function listRepositoryNames(options?: OpenApiRequestOptions) {
  const { client, requestOptions } = resolveOpenApiRequestOptions(options);

  return client.get<ListRepositoryNamesResponse>(
    `${API_PREFIX}/repository-names`,
    requestOptions,
  );
}

export function postCheckUpstreamRepositories(params: PostCheckUpstreamRepositoriesRequest, options?: OpenApiRequestOptions) {
  const { client, requestOptions } = resolveOpenApiRequestOptions(options);

  return client.post<PostCheckUpstreamRepositoriesResponse, PostCheckUpstreamRepositoriesRequest["body"]>(
    `${API_PREFIX}/repositories/check-upstream`,
    params.body,
    requestOptions,
  );
}

export function listRepositoryOciTags(params: ListRepositoryOciTagsRequest, options?: OpenApiRequestOptions) {
  const { client, requestOptions } = resolveOpenApiRequestOptions(options);

  return client.get<ListRepositoryOciTagsResponse>(
    buildOpenApiPath(`${API_PREFIX}/repositories/{id}/oci-tags`, params.path),
    requestOptions,
  );
}

export function getRepositoryOciDetail(params: GetRepositoryOciDetailRequest, options?: OpenApiRequestOptions) {
  const { client, requestOptions } = resolveOpenApiRequestOptions(options);

  return client.get<GetRepositoryOciDetailResponse>(
    appendOpenApiQuery(buildOpenApiPath(`${API_PREFIX}/repositories/{id}/oci-detail`, params.path), params?.query),
    requestOptions,
  );
}

export function listRepositoryArtifacts(params: ListRepositoryArtifactsRequest, options?: OpenApiRequestOptions) {
  const { client, requestOptions } = resolveOpenApiRequestOptions(options);

  return client.get<ListRepositoryArtifactsResponse>(
    appendOpenApiQuery(buildOpenApiPath(`${API_PREFIX}/repositories/{id}/artifacts`, params.path), params?.query),
    requestOptions,
  );
}

export function deleteRepositoryArtifacts(params: DeleteRepositoryArtifactsRequest, options?: OpenApiRequestOptions) {
  const { client, requestOptions } = resolveOpenApiRequestOptions(options);

  return client.delete<DeleteRepositoryArtifactsResponse, unknown>(
    appendOpenApiQuery(buildOpenApiPath(`${API_PREFIX}/repositories/{id}/artifacts`, params.path), params?.query),
    undefined,
    requestOptions,
  );
}

export function createRepositoryUploads(params: CreateRepositoryUploadsRequest, options?: OpenApiRequestOptions) {
  const { client, requestOptions } = resolveOpenApiRequestOptions(options);

  return client.post<CreateRepositoryUploadsResponse, unknown>(
    buildOpenApiPath(`${API_PREFIX}/repositories/{id}/uploads`, params.path),
    undefined,
    requestOptions,
  );
}

export function getRepositoryUploads(params: GetRepositoryUploadsRequest, options?: OpenApiRequestOptions) {
  const { client, requestOptions } = resolveOpenApiRequestOptions(options);

  return client.get<GetRepositoryUploadsResponse>(
    buildOpenApiPath(`${API_PREFIX}/repositories/{id}/uploads/{uploadID}`, params.path),
    requestOptions,
  );
}

export function deleteRepositoryUploads(params: DeleteRepositoryUploadsRequest, options?: OpenApiRequestOptions) {
  const { client, requestOptions } = resolveOpenApiRequestOptions(options);

  return client.delete<DeleteRepositoryUploadsResponse, unknown>(
    buildOpenApiPath(`${API_PREFIX}/repositories/{id}/uploads/{uploadID}`, params.path),
    undefined,
    requestOptions,
  );
}

export function postCommitRepositoryUploads(params: PostCommitRepositoryUploadsRequest, options?: OpenApiRequestOptions) {
  const { client, requestOptions } = resolveOpenApiRequestOptions(options);

  return client.post<PostCommitRepositoryUploadsResponse, unknown>(
    buildOpenApiPath(`${API_PREFIX}/repositories/{id}/uploads/{uploadID}/commit`, params.path),
    undefined,
    requestOptions,
  );
}

export function deleteRepositoryPublications(params: DeleteRepositoryPublicationsRequest, options?: OpenApiRequestOptions) {
  const { client, requestOptions } = resolveOpenApiRequestOptions(options);

  return client.delete<DeleteRepositoryPublicationsResponse, unknown>(
    buildOpenApiPath(`${API_PREFIX}/repositories/{id}/publications/{publicationID}`, params.path),
    undefined,
    requestOptions,
  );
}

export function postYankRepositoryPublications(params: PostYankRepositoryPublicationsRequest, options?: OpenApiRequestOptions) {
  const { client, requestOptions } = resolveOpenApiRequestOptions(options);

  return client.post<PostYankRepositoryPublicationsResponse, PostYankRepositoryPublicationsRequest["body"]>(
    buildOpenApiPath(`${API_PREFIX}/repositories/{id}/publications/{publicationID}/yank`, params.path),
    params.body,
    requestOptions,
  );
}

export function postDisabledRepository(params: PostDisabledRepositoryRequest, options?: OpenApiRequestOptions) {
  const { client, requestOptions } = resolveOpenApiRequestOptions(options);

  return client.post<PostDisabledRepositoryResponse, PostDisabledRepositoryRequest["body"]>(
    buildOpenApiPath(`${API_PREFIX}/repositories/{id}/disabled`, params.path),
    params.body,
    requestOptions,
  );
}

export function getRepositoryDangling(params: GetRepositoryDanglingRequest, options?: OpenApiRequestOptions) {
  const { client, requestOptions } = resolveOpenApiRequestOptions(options);

  return client.get<GetRepositoryDanglingResponse>(
    buildOpenApiPath(`${API_PREFIX}/repositories/{id}/dangling`, params.path),
    requestOptions,
  );
}

export function listRepositoryArtifactsLabels(params: ListRepositoryArtifactsLabelsRequest, options?: OpenApiRequestOptions) {
  const { client, requestOptions } = resolveOpenApiRequestOptions(options);

  return client.get<ListRepositoryArtifactsLabelsResponse>(
    appendOpenApiQuery(buildOpenApiPath(`${API_PREFIX}/repositories/{id}/artifacts/labels`, params.path), params?.query),
    requestOptions,
  );
}

export function createRepositoryArtifactsLabels(params: CreateRepositoryArtifactsLabelsRequest, options?: OpenApiRequestOptions) {
  const { client, requestOptions } = resolveOpenApiRequestOptions(options);

  return client.post<CreateRepositoryArtifactsLabelsResponse, CreateRepositoryArtifactsLabelsRequest["body"]>(
    buildOpenApiPath(`${API_PREFIX}/repositories/{id}/artifacts/labels`, params.path),
    params.body,
    requestOptions,
  );
}

export function deleteRepositoryArtifactsLabels(params: DeleteRepositoryArtifactsLabelsRequest, options?: OpenApiRequestOptions) {
  const { client, requestOptions } = resolveOpenApiRequestOptions(options);

  return client.delete<DeleteRepositoryArtifactsLabelsResponse, unknown>(
    appendOpenApiQuery(buildOpenApiPath(`${API_PREFIX}/repositories/{id}/artifacts/labels`, params.path), params?.query),
    undefined,
    requestOptions,
  );
}

export function postBulkRepositoryArtifactsLabels(params: PostBulkRepositoryArtifactsLabelsRequest, options?: OpenApiRequestOptions) {
  const { client, requestOptions } = resolveOpenApiRequestOptions(options);

  return client.post<PostBulkRepositoryArtifactsLabelsResponse, PostBulkRepositoryArtifactsLabelsRequest["body"]>(
    buildOpenApiPath(`${API_PREFIX}/repositories/{id}/artifacts/labels/bulk`, params.path),
    params.body,
    requestOptions,
  );
}

export function postBulkDeleteRepositoryArtifacts(params: PostBulkDeleteRepositoryArtifactsRequest, options?: OpenApiRequestOptions) {
  const { client, requestOptions } = resolveOpenApiRequestOptions(options);

  return client.post<PostBulkDeleteRepositoryArtifactsResponse, PostBulkDeleteRepositoryArtifactsRequest["body"]>(
    buildOpenApiPath(`${API_PREFIX}/repositories/{id}/artifacts/bulk-delete`, params.path),
    params.body,
    requestOptions,
  );
}

export function postValidateUploadRepositoryArtifacts(params: PostValidateUploadRepositoryArtifactsRequest, options?: OpenApiRequestOptions) {
  const { client, requestOptions } = resolveOpenApiRequestOptions(options);

  return client.post<PostValidateUploadRepositoryArtifactsResponse, PostValidateUploadRepositoryArtifactsRequest["body"]>(
    buildOpenApiPath(`${API_PREFIX}/repositories/{id}/artifacts/validate-upload`, params.path),
    params.body,
    requestOptions,
  );
}

export function updateRepositoryArtifactsUpload(params: UpdateRepositoryArtifactsUploadRequest, options?: OpenApiRequestOptions) {
  const { client, requestOptions } = resolveOpenApiRequestOptions(options);

  return client.put<UpdateRepositoryArtifactsUploadResponse, unknown>(
    appendOpenApiQuery(buildOpenApiPath(`${API_PREFIX}/repositories/{id}/artifacts/upload`, params.path), params?.query),
    undefined,
    requestOptions,
  );
}

export function getRepositoryUpstreamHealth(params: GetRepositoryUpstreamHealthRequest, options?: OpenApiRequestOptions) {
  const { client, requestOptions } = resolveOpenApiRequestOptions(options);

  return client.get<GetRepositoryUpstreamHealthResponse>(
    buildOpenApiPath(`${API_PREFIX}/repositories/{id}/upstream-health`, params.path),
    requestOptions,
  );
}

export function listRepositoryPermissions(params: ListRepositoryPermissionsRequest, options?: OpenApiRequestOptions) {
  const { client, requestOptions } = resolveOpenApiRequestOptions(options);

  return client.get<ListRepositoryPermissionsResponse>(
    buildOpenApiPath(`${API_PREFIX}/repositories/{id}/permissions`, params.path),
    requestOptions,
  );
}

export function listRepositoryTokens(params: ListRepositoryTokensRequest, options?: OpenApiRequestOptions) {
  const { client, requestOptions } = resolveOpenApiRequestOptions(options);

  return client.get<ListRepositoryTokensResponse>(
    buildOpenApiPath(`${API_PREFIX}/repositories/{id}/tokens`, params.path),
    requestOptions,
  );
}
