// This file is generated by scripts/openapi-codegen.mjs.
// Source: src/openapi/openapi.yaml (repository root)
// OpenAPI: forklift API 0.1.0

import type {
  ArtifactBulkDeleteInput,
  ArtifactBulkLabelInput,
  ArtifactBulkResult,
  ArtifactForceDeleteResult,
  ArtifactLabelInput,
  ArtifactLabelList,
  ArtifactList,
  ArtifactPurgeResult,
  ArtifactUploadResult,
  AuditLogList,
  DanglingRef,
  OCIArtifactDetail,
  OCITagInfo,
  PublicationLifecycleResult,
  PublicationYankInput,
  RepoPermission,
  RepoToken,
  Repository,
  RepositoryCreate,
  RepositoryDisabledInput,
  RepositoryInput,
  RepositoryListItem,
  RepositoryName,
  RepositorySecurityInput,
  UploadPlan,
  UploadResult,
  UploadSession,
  UploadValidationInput,
  UpstreamCheckInput,
  UpstreamHealth
} from "../openapi-types";

export type ListRepositoriesResponse = RepositoryListItem[];

export type CreateRepositoriesRequest = { body: RepositoryCreate };
export type CreateRepositoriesResponse = Repository;

export type GetRepositoryRequest = { path: { id: number } };
export type GetRepositoryResponse = RepositoryListItem;

export type UpdateRepositoryRequest = { path: { id: number }; body: RepositoryInput };
export type UpdateRepositoryResponse = Repository;

export type DeleteRepositoryRequest = { path: { id: number } };
export type DeleteRepositoryResponse = void;

export type UpdateRepositorySecurityRequest = { path: { id: number }; body: RepositorySecurityInput };
export type UpdateRepositorySecurityResponse = Repository;

export type ListRepositoryAuditLogsRequest = { path: { id: number }; query?: { event?: "view" | "download" | "upload" | "delete" | "ttl.expire" | "vuln.block" | "license.block" | "upload.metadata" | "upload.reject" | "upload.cancel" | "repo.create" | "repo.update" | "repo.delete" | "approval.request" | "approval.approve" | "approval.reject" | "deny.create" | "deny.delete" | "deny.block"; limit?: number; offset?: number } };
export type ListRepositoryAuditLogsResponse = AuditLogList;

export type ListRepositoryNamesResponse = RepositoryName[];

export type PostCheckUpstreamRepositoriesRequest = { body: UpstreamCheckInput };
export type PostCheckUpstreamRepositoriesResponse = UpstreamHealth;

export type ListRepositoryOciTagsRequest = { path: { id: number } };
export type ListRepositoryOciTagsResponse = { tags: OCITagInfo[]; };

export type GetRepositoryOciDetailRequest = { path: { id: number }; query?: { name: string; ref: string } };
export type GetRepositoryOciDetailResponse = OCIArtifactDetail;

export type ListRepositoryArtifactsRequest = { path: { id: number }; query?: { q?: string; filter?: "labeled" | "scanned" | "clean" | "vulnerable" | "licensed" | "broken"; regex?: boolean; limit?: number; offset?: number; prefix?: string } };
export type ListRepositoryArtifactsResponse = ArtifactList;

export type DeleteRepositoryArtifactsRequest = { path: { id: number }; query?: { path?: string; force?: boolean } };
export type DeleteRepositoryArtifactsResponse = ArtifactPurgeResult | ArtifactForceDeleteResult;

export type CreateRepositoryUploadsRequest = { path: { id: number } };
export type CreateRepositoryUploadsResponse = ArtifactUploadResult;

export type GetRepositoryUploadsRequest = { path: { id: number; uploadID: string } };
export type GetRepositoryUploadsResponse = UploadSession;

export type DeleteRepositoryUploadsRequest = { path: { id: number; uploadID: string } };
export type DeleteRepositoryUploadsResponse = void;

export type PostCommitRepositoryUploadsRequest = { path: { id: number; uploadID: string } };
export type PostCommitRepositoryUploadsResponse = ArtifactUploadResult;

export type DeleteRepositoryPublicationsRequest = { path: { id: number; publicationID: string } };
export type DeleteRepositoryPublicationsResponse = PublicationLifecycleResult;

export type PostYankRepositoryPublicationsRequest = { path: { id: number; publicationID: string }; body: PublicationYankInput };
export type PostYankRepositoryPublicationsResponse = PublicationLifecycleResult;

export type PostDisabledRepositoryRequest = { path: { id: number }; body: RepositoryDisabledInput };
export type PostDisabledRepositoryResponse = Repository;

export type GetRepositoryDanglingRequest = { path: { id: number } };
export type GetRepositoryDanglingResponse = DanglingRef[];

export type ListRepositoryArtifactsLabelsRequest = { path: { id: number }; query?: { path: string } };
export type ListRepositoryArtifactsLabelsResponse = ArtifactLabelList;

export type CreateRepositoryArtifactsLabelsRequest = { path: { id: number }; body: ArtifactLabelInput };
export type CreateRepositoryArtifactsLabelsResponse = ArtifactLabelList;

export type DeleteRepositoryArtifactsLabelsRequest = { path: { id: number }; query?: { path: string; label: string } };
export type DeleteRepositoryArtifactsLabelsResponse = ArtifactLabelList;

export type PostBulkRepositoryArtifactsLabelsRequest = { path: { id: number }; body: ArtifactBulkLabelInput };
export type PostBulkRepositoryArtifactsLabelsResponse = ArtifactBulkResult;

export type PostBulkDeleteRepositoryArtifactsRequest = { path: { id: number }; body: ArtifactBulkDeleteInput };
export type PostBulkDeleteRepositoryArtifactsResponse = ArtifactBulkResult;

export type PostValidateUploadRepositoryArtifactsRequest = { path: { id: number }; body: UploadValidationInput };
export type PostValidateUploadRepositoryArtifactsResponse = UploadPlan;

export type UpdateRepositoryArtifactsUploadRequest = { path: { id: number }; query?: { path: string } };
export type UpdateRepositoryArtifactsUploadResponse = UploadResult;

export type GetRepositoryUpstreamHealthRequest = { path: { id: number } };
export type GetRepositoryUpstreamHealthResponse = UpstreamHealth;

export type ListRepositoryPermissionsRequest = { path: { id: number } };
export type ListRepositoryPermissionsResponse = RepoPermission[];

export type ListRepositoryTokensRequest = { path: { id: number } };
export type ListRepositoryTokensResponse = RepoToken[];
