{{- if not .Values.webhook.certManager.enabled }}
{{- include "argocd-canary-gate.certs" . -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-tls" (include "argocd-canary-gate.fullname" .) }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "argocd-canary-gate.labels" . | nindent 4 }}
type: kubernetes.io/tls
data:
  tls.crt: {{ .Values.generatedCerts.cert }}
  tls.key: {{ .Values.generatedCerts.key }}
  ca.crt: {{ .Values.generatedCerts.ca }}
{{- end }}
