#!/usr/bin/env python3
"""Render the generated CustomResourceDefinition into the Helm chart.

The schema is authored once, in Rust: `AlertRuleSpec` in src/alerts/crd.rs.
`trivy-collector crd` prints the definition kube derives from that type, and
this wraps it in the chart's conditional and label helpers. Nothing about the
schema is hand-written, so the chart cannot drift from the code the collector
reads.

Usage: cargo run -q -- crd | scripts/render-crd.py <output.yaml>
"""

import json
import sys

import yaml

HEADER = """{{- if .Values.crds.install }}
{{- /*
  Generated by `make crd` from AlertRuleSpec in src/alerts/crd.rs. Do not edit:
  change the Rust type and regenerate.

  This sits in templates/ rather than crds/ because Helm never upgrades anything
  in crds/. A schema change there would silently not apply, and this chart is
  installed through Argo CD, where that failure is invisible.
*/}}
"""

FOOTER = "{{- end }}\n"

LABELS = '''  labels:
    {{- include "trivy-collector.labels" . | nindent 4 }}
    {{- with .Values.crds.additionalLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- if or .Values.crds.keep .Values.crds.annotations }}
  annotations:
    {{- if .Values.crds.keep }}
    helm.sh/resource-policy: keep
    {{- end }}
    {{- with .Values.crds.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- end }}
'''


def collapse_descriptions(node):
    """Fold Rust doc-comment line breaks into single spaces.

    A `///` comment wraps at the source's column limit, and those newlines
    survive into the schema, where PyYAML renders them as multi-line folded
    scalars with escaped quotes. The line breaks carry no meaning in a
    description, so drop them and let the YAML dumper wrap.
    """
    if isinstance(node, dict):
        for key, value in node.items():
            if key == "description" and isinstance(value, str):
                node[key] = " ".join(value.split())
            else:
                collapse_descriptions(value)
    elif isinstance(node, list):
        for item in node:
            collapse_descriptions(item)


def main() -> int:
    if len(sys.argv) != 2:
        print(__doc__, file=sys.stderr)
        return 2

    crd = json.load(sys.stdin)
    collapse_descriptions(crd)
    name = crd["metadata"]["name"]

    # Helm owns metadata: the chart's labels and the operator's annotations.
    # Everything below it comes from the generated document verbatim.
    head = yaml.safe_dump(
        {"apiVersion": crd["apiVersion"], "kind": crd["kind"]},
        sort_keys=False,
        default_flow_style=False,
    )
    body = yaml.safe_dump(
        {"spec": crd["spec"]},
        sort_keys=False,
        default_flow_style=False,
        width=100,
    )

    with open(sys.argv[1], "w") as f:
        f.write(HEADER)
        f.write(head)
        f.write("metadata:\n")
        f.write(f"  name: {name}\n")
        f.write(LABELS)
        f.write(body)
        f.write(FOOTER)

    print(f"wrote {sys.argv[1]} ({name})", file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(main())
