// This file is generated by scripts/openapi-codegen.mjs.
// Source: src/openapi/openapi.yaml (repository root)
// OpenAPI: forklift API 0.1.0

import {
  buildOpenApiPath,
  resolveOpenApiRequestOptions,
  type OpenApiRequestOptions,
} from "@/services/v1/openapi-runtime";

import { API_PREFIX } from "@/services/paths";

import type {
  CreateTokensRequest,
  CreateTokensResponse,
  CreateUserTokensRequest,
  CreateUserTokensResponse,
  DeleteTokenRequest,
  DeleteTokenResponse,
  DeleteUserTokensRequest,
  DeleteUserTokensResponse,
  ListTokensResponse,
  ListUserTokensRequest,
  ListUserTokensResponse,
  UpdateTokenRequest,
  UpdateTokenResponse,
  UpdateUserTokensRequest,
  UpdateUserTokensResponse,
} from "./types";

export function listTokens(options?: OpenApiRequestOptions) {
  const { client, requestOptions } = resolveOpenApiRequestOptions(options);

  return client.get<ListTokensResponse>(
    `${API_PREFIX}/tokens`,
    requestOptions,
  );
}

export function createTokens(params: CreateTokensRequest, options?: OpenApiRequestOptions) {
  const { client, requestOptions } = resolveOpenApiRequestOptions(options);

  return client.post<CreateTokensResponse, CreateTokensRequest["body"]>(
    `${API_PREFIX}/tokens`,
    params.body,
    requestOptions,
  );
}

export function updateToken(params: UpdateTokenRequest, options?: OpenApiRequestOptions) {
  const { client, requestOptions } = resolveOpenApiRequestOptions(options);

  return client.patch<UpdateTokenResponse, UpdateTokenRequest["body"]>(
    buildOpenApiPath(`${API_PREFIX}/tokens/{id}`, params.path),
    params.body,
    requestOptions,
  );
}

export function deleteToken(params: DeleteTokenRequest, options?: OpenApiRequestOptions) {
  const { client, requestOptions } = resolveOpenApiRequestOptions(options);

  return client.delete<DeleteTokenResponse, unknown>(
    buildOpenApiPath(`${API_PREFIX}/tokens/{id}`, params.path),
    undefined,
    requestOptions,
  );
}

export function listUserTokens(params: ListUserTokensRequest, options?: OpenApiRequestOptions) {
  const { client, requestOptions } = resolveOpenApiRequestOptions(options);

  return client.get<ListUserTokensResponse>(
    buildOpenApiPath(`${API_PREFIX}/users/{id}/tokens`, params.path),
    requestOptions,
  );
}

export function createUserTokens(params: CreateUserTokensRequest, options?: OpenApiRequestOptions) {
  const { client, requestOptions } = resolveOpenApiRequestOptions(options);

  return client.post<CreateUserTokensResponse, CreateUserTokensRequest["body"]>(
    buildOpenApiPath(`${API_PREFIX}/users/{id}/tokens`, params.path),
    params.body,
    requestOptions,
  );
}

export function updateUserTokens(params: UpdateUserTokensRequest, options?: OpenApiRequestOptions) {
  const { client, requestOptions } = resolveOpenApiRequestOptions(options);

  return client.patch<UpdateUserTokensResponse, UpdateUserTokensRequest["body"]>(
    buildOpenApiPath(`${API_PREFIX}/users/{id}/tokens/{tokenID}`, params.path),
    params.body,
    requestOptions,
  );
}

export function deleteUserTokens(params: DeleteUserTokensRequest, options?: OpenApiRequestOptions) {
  const { client, requestOptions } = resolveOpenApiRequestOptions(options);

  return client.delete<DeleteUserTokensResponse, unknown>(
    buildOpenApiPath(`${API_PREFIX}/users/{id}/tokens/{tokenID}`, params.path),
    undefined,
    requestOptions,
  );
}
