// This file is generated by scripts/openapi-query-options.mjs.
// Source: src/openapi/openapi.yaml (repository root)
// OpenAPI: forklift API 0.1.0

import { queryOptions } from "@tanstack/react-query";

import { type HttpClient } from "@/lib/http/client/http-client";
import { openApiQueryKeys } from "@/query/v1/openapi-query-keys";
import {
  listTokens,
  listUserTokens,
} from "@/services/v1/tokens/api";
import type {
  ListUserTokensRequest,
} from "@/services/v1/tokens/types";
export function createTokensOpenApiQueryOptions(client: HttpClient) {
  return {
    listTokens: () =>
      queryOptions({
        queryKey: openApiQueryKeys.listTokens(),
        queryFn: ({ signal }) =>
          listTokens({ signal, client }),
      }),
    listUserTokens: (params: ListUserTokensRequest) =>
      queryOptions({
        queryKey: openApiQueryKeys.listUserTokens(params),
        queryFn: ({ signal }) =>
          listUserTokens(params, { signal, client }),
      }),
  } as const;
}
