// This file is generated by scripts/openapi-codegen.mjs.
// Source: src/openapi/openapi.yaml (repository root)
// OpenAPI: forklift API 0.1.0

import {
  buildOpenApiPath,
  resolveOpenApiRequestOptions,
  type OpenApiRequestOptions,
} from "@/services/v1/openapi-runtime";

import { API_PREFIX } from "@/services/paths";

import type {
  CreateUserRolesRequest,
  CreateUserRolesResponse,
  CreateUsersRequest,
  CreateUsersResponse,
  DeleteUserRequest,
  DeleteUserResponse,
  DeleteUserRolesRequest,
  DeleteUserRolesResponse,
  ListUsersResponse,
  PostImpersonateUserRequest,
  PostImpersonateUserResponse,
  UpdateUserRequest,
  UpdateUserResponse,
} from "./types";

export function listUsers(options?: OpenApiRequestOptions) {
  const { client, requestOptions } = resolveOpenApiRequestOptions(options);

  return client.get<ListUsersResponse>(
    `${API_PREFIX}/users`,
    requestOptions,
  );
}

export function createUsers(params: CreateUsersRequest, options?: OpenApiRequestOptions) {
  const { client, requestOptions } = resolveOpenApiRequestOptions(options);

  return client.post<CreateUsersResponse, CreateUsersRequest["body"]>(
    `${API_PREFIX}/users`,
    params.body,
    requestOptions,
  );
}

export function updateUser(params: UpdateUserRequest, options?: OpenApiRequestOptions) {
  const { client, requestOptions } = resolveOpenApiRequestOptions(options);

  return client.put<UpdateUserResponse, UpdateUserRequest["body"]>(
    buildOpenApiPath(`${API_PREFIX}/users/{id}`, params.path),
    params.body,
    requestOptions,
  );
}

export function deleteUser(params: DeleteUserRequest, options?: OpenApiRequestOptions) {
  const { client, requestOptions } = resolveOpenApiRequestOptions(options);

  return client.delete<DeleteUserResponse, unknown>(
    buildOpenApiPath(`${API_PREFIX}/users/{id}`, params.path),
    undefined,
    requestOptions,
  );
}

export function postImpersonateUser(params: PostImpersonateUserRequest, options?: OpenApiRequestOptions) {
  const { client, requestOptions } = resolveOpenApiRequestOptions(options);

  return client.post<PostImpersonateUserResponse, PostImpersonateUserRequest["body"]>(
    buildOpenApiPath(`${API_PREFIX}/users/{id}/impersonate`, params.path),
    params.body,
    requestOptions,
  );
}

export function createUserRoles(params: CreateUserRolesRequest, options?: OpenApiRequestOptions) {
  const { client, requestOptions } = resolveOpenApiRequestOptions(options);

  return client.post<CreateUserRolesResponse, CreateUserRolesRequest["body"]>(
    buildOpenApiPath(`${API_PREFIX}/users/{id}/roles`, params.path),
    params.body,
    requestOptions,
  );
}

export function deleteUserRoles(params: DeleteUserRolesRequest, options?: OpenApiRequestOptions) {
  const { client, requestOptions } = resolveOpenApiRequestOptions(options);

  return client.delete<DeleteUserRolesResponse, unknown>(
    buildOpenApiPath(`${API_PREFIX}/users/{id}/roles/{roleID}`, params.path),
    undefined,
    requestOptions,
  );
}
