{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "external-ebs-autoresizer.fullname" . }}
  labels:
    {{- include "external-ebs-autoresizer.labels" . | nindent 4 }}
rules:
  {{- if (include "external-ebs-autoresizer.nodeAccessEnabled" .) }}
  - apiGroups: [""]
    resources: ["nodes"]
    verbs:
      - get
      - list
      - patch
  {{- end }}
  {{- if (include "external-ebs-autoresizer.protectiveCordonEnabled" .) }}
  - apiGroups: [""]
    resources: ["nodes/status"]
    verbs:
      - patch
  {{- end }}
  - apiGroups: [""]
    resources: ["pods"]
    verbs:
      - list
  - apiGroups: ["apps"]
    resources: ["statefulsets"]
    verbs:
      - list
  - apiGroups: [""]
    resources: ["persistentvolumeclaims", "persistentvolumes"]
    verbs:
      - get
      - list
      - patch
  - apiGroups: [""]
    resources: ["events"]
    verbs:
      - create
      - patch
      - update
{{- end }}
