// This file is generated by scripts/openapi-codegen.mjs.
// Source: src/openapi/openapi.yaml (repository root)
// OpenAPI: forklift API 0.1.0

import {
  buildOpenApiPath,
  resolveOpenApiRequestOptions,
  type OpenApiRequestOptions,
} from "@/services/v1/openapi-runtime";

import { API_PREFIX } from "@/services/paths";

import type {
  CreateNotificationReceiversRequest,
  CreateNotificationReceiversResponse,
  DeleteNotificationReceiversRequest,
  DeleteNotificationReceiversResponse,
  GetRepositoryNotificationSampleRequest,
  GetRepositoryNotificationSampleResponse,
  ListNotificationReceiversResponse,
  PostSampleRepositoryNotificationRequest,
  PostSampleRepositoryNotificationResponse,
  PostTestNotificationReceiversRequest,
  PostTestNotificationReceiversResponse,
  PostTestNotificationRequest,
  PostTestNotificationResponse,
  UpdateNotificationReceiversRequest,
  UpdateNotificationReceiversResponse,
} from "./types";

export function listNotificationReceivers(options?: OpenApiRequestOptions) {
  const { client, requestOptions } = resolveOpenApiRequestOptions(options);

  return client.get<ListNotificationReceiversResponse>(
    `${API_PREFIX}/notification/receivers`,
    requestOptions,
  );
}

export function createNotificationReceivers(params: CreateNotificationReceiversRequest, options?: OpenApiRequestOptions) {
  const { client, requestOptions } = resolveOpenApiRequestOptions(options);

  return client.post<CreateNotificationReceiversResponse, CreateNotificationReceiversRequest["body"]>(
    `${API_PREFIX}/notification/receivers`,
    params.body,
    requestOptions,
  );
}

export function updateNotificationReceivers(params: UpdateNotificationReceiversRequest, options?: OpenApiRequestOptions) {
  const { client, requestOptions } = resolveOpenApiRequestOptions(options);

  return client.put<UpdateNotificationReceiversResponse, UpdateNotificationReceiversRequest["body"]>(
    buildOpenApiPath(`${API_PREFIX}/notification/receivers/{id}`, params.path),
    params.body,
    requestOptions,
  );
}

export function deleteNotificationReceivers(params: DeleteNotificationReceiversRequest, options?: OpenApiRequestOptions) {
  const { client, requestOptions } = resolveOpenApiRequestOptions(options);

  return client.delete<DeleteNotificationReceiversResponse, unknown>(
    buildOpenApiPath(`${API_PREFIX}/notification/receivers/{id}`, params.path),
    undefined,
    requestOptions,
  );
}

export function postTestNotificationReceivers(params: PostTestNotificationReceiversRequest, options?: OpenApiRequestOptions) {
  const { client, requestOptions } = resolveOpenApiRequestOptions(options);

  return client.post<PostTestNotificationReceiversResponse, unknown>(
    buildOpenApiPath(`${API_PREFIX}/notification/receivers/{id}/test`, params.path),
    undefined,
    requestOptions,
  );
}

export function postTestNotification(params: PostTestNotificationRequest, options?: OpenApiRequestOptions) {
  const { client, requestOptions } = resolveOpenApiRequestOptions(options);

  return client.post<PostTestNotificationResponse, PostTestNotificationRequest["body"]>(
    `${API_PREFIX}/notification/test`,
    params.body,
    requestOptions,
  );
}

export function getRepositoryNotificationSample(params: GetRepositoryNotificationSampleRequest, options?: OpenApiRequestOptions) {
  const { client, requestOptions } = resolveOpenApiRequestOptions(options);

  return client.get<GetRepositoryNotificationSampleResponse>(
    buildOpenApiPath(`${API_PREFIX}/repositories/{id}/notification/sample`, params.path),
    requestOptions,
  );
}

export function postSampleRepositoryNotification(params: PostSampleRepositoryNotificationRequest, options?: OpenApiRequestOptions) {
  const { client, requestOptions } = resolveOpenApiRequestOptions(options);

  return client.post<PostSampleRepositoryNotificationResponse, unknown>(
    buildOpenApiPath(`${API_PREFIX}/repositories/{id}/notification/sample`, params.path),
    undefined,
    requestOptions,
  );
}
