// This file is generated by scripts/openapi-query-options.mjs.
// Source: src/openapi/openapi.yaml (repository root)
// OpenAPI: forklift API 0.1.0

import { queryOptions } from "@tanstack/react-query";

import { type HttpClient } from "@/lib/http/client/http-client";
import { openApiQueryKeys } from "@/query/v1/openapi-query-keys";
import {
  listUsers,
} from "@/services/v1/users/api";

export function createUsersOpenApiQueryOptions(client: HttpClient) {
  return {
    listUsers: () =>
      queryOptions({
        queryKey: openApiQueryKeys.listUsers(),
        queryFn: ({ signal }) =>
          listUsers({ signal, client }),
      }),
  } as const;
}
